components/Layout.tsx

Fixing validation issue

---

components/JsonEditor.tsx
components/StyledMarkdown.tsx
package-lock.json
package.json
pages/learn/getting-started-step-by-step.md

- fixed anchor links on `learn/getting-started` page, id needed full title
- there are still `Violation] 'click' handler took 175ms`
- updated @docsearch/react to latest, resolved error 
- took out `prefetch` on Link in `StyledMarkdown`, Next no longer uses
- hide console.log in `JsonEditor`

fix anchor link in learn/getting-started, also updated docsearch package

---

next.config.js
pages/index.page.tsx

updated href on the `Open Slack Workspace` section

fix slack workspace path

---

components/Layout.tsx
next.config.js

updated doc structure
added subtitle with different styles

docs structure

---

components/Layout.tsx

Fix menu order for Reference

---

pages/learn/glossary.md

Brings the glossary back in sync.

Bring the glossary back in sync

---

components/Layout.tsx
pages/draft-05/readme.md
pages/draft-06/json-hyper-schema-release-notes.md
pages/draft-06/json-schema-release-notes.md
pages/draft-06/readme.md
pages/draft-07/json-hyper-schema-release-notes.md
pages/draft-07/json-schema-release-notes.md
pages/draft-07/readme.md
pages/draft/2019-09/release-notes.md
pages/draft/2020-12/release-notes.md
pages/learn/glossary.md
pages/specification-links.md
pages/understanding-json-schema/about.md
pages/understanding-json-schema/what-is-json-schema.md

Improvements in navigation

---

components/Layout.tsx
pages/understanding-json-schema/credits.md

Changes in menu of specification

Changes in menu of specification

---

pages/learn/getting-started-step-by-step.md
pages/overview/what-is-jsonschema.md

Adds new drafts for: 
- Overview (what is JSON Schema)
- Creating your first schema

9 docs release 1

---

pages/overview/what-is-jsonschema.md

I have added line breaks before every code snippet for proper visualization.

[Docs] Fix visualization of code snippets 

---

components/Layout.tsx
components/Sidebar.tsx
pages/blog/index.page.tsx
pages/index.page.tsx

Clean up of alignment, padding margins
- nav transitions
- doc width
- blog filter btn
- supported section

clean up index, blog, and doc pages

---

components/Layout.tsx
pages/index.page.tsx

Last changes to improve style of supported by logos and header menus.

Last changes

---

pages/blog/posts/[slug].page.tsx

Fix blog page

---

components/Layout.tsx
pages/blog/posts/[slug].page.tsx
pages/index.page.tsx

- Events style.
- Events sorting.
- Improve texts.

Website final iterations

---

components/Layout.tsx
pages/blog/posts/[slug].page.tsx
pages/implementations/index.page.tsx

- Better padding in blog post view.
- Better mobile view for implementations.
- Fix link in mobile header

Changes before final roll-out

---

components/Sidebar.tsx
pages/understanding-json-schema/reference/_index.md

- improve the reference section of understanding json schema
- Improve sidebar structure

Changes in sidebar and understanding json schema

---

components/Sidebar.tsx
pages/understanding-json-schema/structuring.md

Content migration for understanding JSON Schema

Content migration for understanding JSON Schema

---

components/Layout.tsx

Change to make sure the community anchor navigation works for in mobile.

Change to make sure mobile navigation works for community

---

pages/index.page.tsx

Increase padding for adapters text

Increase padding for adapters text

---

components/Layout.tsx

Improve behaviour of carbonads

Improve behaviour of carbonads

---

components/Sidebar.tsx

small change to fix sidebar menu

small change to fix sidebar menu

---

pages/understanding-json-schema/_index.md

Related: https://json-schema.slack.com/archives/CB3SS5W5B/p1696433376276519?thread_ts=1694529805.273859&cid=CB3SS5W5B

Fix links of understanding json schema links in landing page.

---

pages/blog/posts/bowtie-intro.md
pages/blog/posts/get-started-with-json-schema-in-node-js.md
pages/blog/posts/w3c-wot-case-study.md
pages/draft-06/json-hyper-schema-release-notes.md
pages/learn/file-system.md
pages/learn/glossary.md
pages/specification-links.md
pages/understanding-json-schema/basics.md
pages/understanding-json-schema/reference/regular_expressions.md
pages/understanding-json-schema/reference/string.md
public/draft/2020-12/draft-bhutton-json-schema-validation-01.html

Fix broken links

---

pages/understanding-json-schema/about.md
pages/understanding-json-schema/basics.md
pages/understanding-json-schema/reference/combining.md
pages/understanding-json-schema/reference/conditionals.md
pages/understanding-json-schema/reference/null.md
pages/understanding-json-schema/reference/object.md
pages/understanding-json-schema/reference/regular_expressions.md
pages/understanding-json-schema/reference/string.md
pages/understanding-json-schema/reference/type.md

Fix issues with next.js navigation in understanding json schema

Fix issues with next.js navigation in understanding json schema

---

components/StyledMarkdown.tsx

Add better style for ordered lists.
Resolves: #92

Add better style for ordered lists

---

pages/index.page.tsx

Fix bug with event dates

---

components/DocsHelp.tsx
pages/[slug].page.tsx
pages/draft-05/[slug].page.tsx
pages/draft-06/[slug].page.tsx
pages/draft-07/[slug].page.tsx
pages/draft/2019-09/[slug].page.tsx
pages/draft/2020-12/[slug].page.tsx
pages/learn/[slug].page.tsx
pages/overview/[slug].page.tsx
pages/understanding-json-schema/[slug].page.tsx
pages/understanding-json-schema/index.page.tsx
pages/understanding-json-schema/reference/[slug].page.tsx
pages/understanding-json-schema/reference/index.page.tsx

Add a help message in the footer of all our docs.

Add a help message in the footer of all our docs.

---

pages/index.page.tsx

Improve the links in the community section

Improve the links in the community section

---

components/Layout.tsx

Added a link to JSON Schema CoC

Added a link to JSON Schema CoC

---

components/Layout.tsx

center links in footer for small devices

center links in footer for small devices

---

pages/index.page.tsx

Center hero logos for small devices

Center hero logos for small devices

---

pages/understanding-json-schema/_index.md

Add copyright message to UJS

---

pages/index.page.tsx

More padding in support us text

More padding in support us text

---

.gitattributes
pages/understanding-json-schema/reference/array.md

Ran into a bunch of weird local problems, but it looked perfect once it ran. What do you think?

add ``unevaluatedItems`` tutorial

---

README.md
components/DocsHelp.tsx
components/Layout.tsx
pages/blog/posts/new-website.md
pages/index.page.tsx

We received feedback regarding broken links of the Join Slack links. This PR fix that.

Fix slack links

---

components/Remember.tsx
components/Sidebar.tsx
pages/implementers/[slug].page.tsx
pages/implementers/_index.md
pages/implementers/index.page.tsx

Adding a landing page and some style for the new section for Implementer resources.

New page for implementers

---

pages/implementers/_index.md

Better wording for implementers landing

Better wording for implementers landing

---

components/DocsHelp.tsx
components/Remember.tsx
pages/implementers/_index.md

Fix channel name of the contribute to the docs message.

Fix channel name

---

components/StyledMarkdown.tsx

Fix blog for small devices

---

pages/understanding-json-schema/reference/_index.md

Fix 404 issues in the website.

Fix 404 issues in the website.

---

pages/learn/getting-started-step-by-step.md

Resolves #169 
Avoid the numbered to have all "1." in the getting started guide.

Solves the issue 169 - Avoid the numbered to have all "1." in the getting started guide

---

pages/index.page.tsx

Fix alignment of community blocks in the landing page

Fix alignment of community blocks in the landing page

---

pages/understanding-json-schema/reference/conditionals.md

Fixes https://github.com/json-schema-org/website/issues/170
In addition to fixing the error I did some editorial cleanup of the whole section.

Fix error in if/then/else on UJS and cleanup

---

pages/blog/posts/interpreting-output.md

typo in json-everything

---

README.md

Add repo status badge

---

components/Layout.tsx
pages/[slug].page.tsx
pages/draft-05/[slug].page.tsx
pages/draft-06/[slug].page.tsx
pages/draft-07/[slug].page.tsx
pages/draft/2019-09/[slug].page.tsx
pages/draft/2020-12/[slug].page.tsx
pages/implementers/[slug].page.tsx
pages/index.page.tsx
pages/learn/[slug].page.tsx
pages/overview/[slug].page.tsx
pages/understanding-json-schema/[slug].page.tsx
pages/understanding-json-schema/reference/[slug].page.tsx

This creates bigger links to join slack and read blog elements in the community section.

Fix extended links for community sections

---

pages/blog/index.page.tsx
styles/globals.css

Add title clarity and blog guidelines

---

.github/workflows/new-implementation.yml
pages/implementations/main.md

Hello,
I'm purposing to add this latest JSON Schema implementation of mine to the list of Web UIs:
> [JSON Schema Form Element](https://github.com/json-schema-form-element/jsfe) is a **Web Components** based, **form UI generator** that support any major custom elements libraries (Shoelace, Material, Carbon, Spectrum…) and / or custom widgets.
Thanks :)

Add JSON Schema Form Element to Web UI implementations

---

pages/blog/index.page.tsx

Add link to access the blog showed in the hero of the blog list.

Add link to access the blog showed in the hero of the blog list.

---

pages/blog/posts/interpreting-output.md

Found some issues in the schemas and results I included in the post.

minor corrections

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/enhancement.md

Add issue templates

---

.github/ISSUE_TEMPLATE/docs.yml

Update docs form issue template

Update docs form issue template

---

components/StyledMarkdown.tsx

List text is a different color from paragraph text

---

pages/index.page.tsx

Improved call to actions for sponsorships

Improved call to actions for sponsorships

---

pages/implementers/interfaces.md

Some found via the `z-schema` implementation's README at https://github.com/zaggino/z-schema?tab=readme-ov-file#features
I've added what I saw thought belonged, but obviously feel free to suggest others.
Closes: #232

Add a few additional interfaces to the common interfaces page.

---

pages/specification-links.md
yarn.lock

Fixes https://github.com/json-schema-org/website/issues/253

Fix broken spec link

---

pages/index.page.tsx

Change Community by Join Slack in primary CTA in Hero page
**Summary**: It will be great to have a Join Slack CTA in the Hero page. We can use for it the Community button because Community is also in the Top Menu.
No

Change Community by Join Slack in primary CTA in Hero page

---

pages/blog/posts/apidays-paris-2023-recap.md

**Summary**: Add link to conference.
No

Add conference link

---

pages/implementations/main.md

**Summary**:
Add [`json-schema-to-ts`](https://github.com/ThomasAribart/json-schema-to-ts) to the list of implementations.
No

Add json-schema-to-ts to implementations

---

pages/understanding-json-schema/conventions.md
pages/understanding-json-schema/reference/array.md
pages/understanding-json-schema/reference/boolean.md
pages/understanding-json-schema/reference/comments.md
pages/understanding-json-schema/reference/null.md
pages/understanding-json-schema/reference/numeric.md
pages/understanding-json-schema/reference/object.md
pages/understanding-json-schema/reference/regular_expressions.md
pages/understanding-json-schema/reference/string.md
pages/understanding-json-schema/reference/type.md

This PR contain the migration of multiple PRs from Understanding JSON Schema repository:
- https://github.com/json-schema-org/understanding-json-schema/pull/198
- https://github.com/json-schema-org/understanding-json-schema/pull/140
- https://github.com/json-schema-org/understanding-json-schema/pull/115

Migration of multiple PRs from Understanding JSON Schema repository

---

pages/implementations/main.md

**Summary**: Per https://github.com/bcherny/json-schema-to-typescript/issues/554
Yes/No

Add json-schema-to-typescript

---

pages/understanding-json-schema/structuring.md

Fix typo in `structuring.md`

---

CONTRIBUTING.md
README.md

**Summary**: Add contribution path for website development
No

Add contribution path for website development

---

.gitmodules
components/Layout.tsx
components/Sidebar.tsx
components/StyledMarkdown.tsx
pages/overview/code-of-conduct/_index.md
pages/overview/code-of-conduct/index.page.tsx

**GitHub Issue:** #278 
Fixes: #278 
**Summary**: Add the Code of Conduct and fix hydration issues due to markdown link references
Changes included:
* Adding the CoC through submodule + symlink
* Fixed hydration issues due to markdown link references
No

Add the Code of Conduct and fix hydration issues due to markdown link references

---

components/JsonEditor.tsx

**Summary**: Fix formatting issues identified by eslint.
Yes/No

Fix some formatting issues identified by eslint.

---

components/StyledMarkdown.tsx

**Summary**: There are some issue to be fixed in master branch due to eslint errors in Cloudflare
Yes/No

Fix eslint messages and new tags formats.

---

pages/understanding-json-schema/reference/non_json_data.md

**GitHub Issue:** #191
**Summary**:
No
removal of some unwanted formats hence does not need ADR

removed unwanted formats

---

pages/understanding-json-schema/reference/regular_expressions.md

**GitHub Issue:** #188 
Fixes #188 
**Summary**:
No
its a small fix, which solves the lazy expression issue

fixed lazy expression issue

---

pages/learn/glossary.md

**GitHub Issue:** #156 
Resolves #156 
**Summary**:
Yes/No

docs: added definition of json hyper-schema

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Add triage labels to issue templates

Triage labels

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Fix issue templates

---

pages/blog/index.page.tsx

Handle Overflow in Blog Space
-  Closes #393 
-  Related to #393 
**Summary**
This pull request addresses the issue of content overflow in the blog space of our website. The changes ensure that the content within the blog space does not overflow its container, improving the readability and user experience.

handled the overflow issue in blog space

---

pages/overview/similar-technologies.md

Content fix
**Summary**
AJV is an implementation as opposed to a similar standard. We already list it on the tools page.
No

Remove AJV from similar technologies

---

.github/workflows/welcome-first-time-contrib.yml

Resolves #346 
**Summary**:
**On first PR:**
Welcome to offical repository for [json-schema.org](https://json-schema.org/). Thanks a lot for creating your first pull request. Please check out our [contributors guide](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md) useful for opening a pull request.<br /> For more details check out [README.md](https://github.com/json-schema-org/website?tab=readme-ov-file#-welcome-to-the-json-schema-website) file.
**On first issue:**
Welcome to offical website repository for [json-schema.org](https://json-schema.org/). Thanks a lot for reporting your first issue. Please check out our [contributors guide](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md) useful for opening a pull request.<br /> For more details check …

ci: add workflow to welcome first-time contributors

---

pages/md-style-guide.md

Small changes to refine the wording of the style guide.

Small changes to style guide.

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Fix projects format in issue templates. Projects assignment is not working as expected.

Fix projects format in issue templates.

---

components/Layout.tsx
styles/globals.css

**GitHub Issue:** #375 
Resolves #375 
**Summary**:
The footer section requires some design enhancements, including alignment issues and excess space below the footer.
**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)** : No

fix: #375 fixes The Footer Section and give a good look 

---

pages/index.page.tsx

Unnecessary top padding and block property.
-  Closes #414 
-  Others? 
**Summary**

remove padding from top issue#414

---

pages/blog/index.page.tsx

Fix this error in cloudflare:
````
16:37:00.050 | Failed to compile.
16:37:00.050 |  
16:37:00.050 | ./pages/blog/index.page.tsx
16:37:00.050 | 1:51  Error: Insert `;`  prettier/prettier
16:37:00.050 | 2:29  Error: Insert `;`  prettier/prettier
16:37:00.051 | 3:29  Error: Insert `;`  prettier/prettier
16:37:00.051 | 4:20  Error: Insert `;`  prettier/prettier
16:37:00.051 | 5:52  Error: Insert `;`  prettier/prettier
16:37:00.051 | 6:33  Error: Insert `;`  prettier/prettier
16:37:00.051 | 7:39  Error: Insert `;`  prettier/prettier
16:37:00.051 | 8:32  Error: Insert `;`  prettier/prettier
16:37:00.051 | 9:47  Error: Insert `;`  prettier/prettier
16:37:00.051 | 10:48  Error: Insert `;`  prettier/prettier
16:37:00.051 | 11:40  Error: Insert `;`  prettier/prettier
16:37:00.052 | 12:50  Error: …
```

fix prettier

---

public/_redirects

The slack redirect using _redirect is not working. Trying different approaches.

fine tune slack redirect

---

.github/workflows/welcome-first-time-contrib.yml

What kind of change does this PR introduce?
This fixed unnecessary Greetings to the new contributors.
Issue Number:
Closes #500 
Screenshots/videos:
If relevant, did you update the documentation?
Not relevant hence no need to update the docs.
Summary
The main goal was to reduce unnecessary greeting comments, to keep the comment section clean.
Does this PR introduce a breaking change?
No

Fix: Issue with workflow to Greeting the new contributor

---

components/Layout.tsx

-  Related to #486  
-  Others? 
**Summary**

Broken alignment in options menu #486

---

pages/implementations/index.page.tsx

- Refactoring: This PR aims to make the implementations table responsive on different screen sizes.
-  Closes #502  
- After refactoring
**Summary**
- Reduced text sizes on smaller screens to optimize table layout.
- Implemented horizontal scrolling on the table to enhance responsiveness and ensure complete content visibility.
No

Bug-UI: Make table responsive

---

components/Layout.tsx
components/ScrollButton.tsx
next.config.js
public/img/scroll.svg

Adding the scroll to top button in the website.
-  Closes #503 
**Summary**
Scroll to top button added.
No

Feat: Adding Scroll Button

---

.github/workflows/welcome-first-time-contrib.yml
components/Layout.tsx

-  Closes #516  
-  Others? 
**Summary**

Bug: Problem with workflows/welcome-first-time-contrib.yml

---

pages/understanding-json-schema/reference/combining.md

Fixed typos in `combining.md` .
#513 
-  Closes #513 
No

Fixed typos on pages

---

components/Layout.tsx
components/Sidebar.tsx

This PR brings back the changes of footer that was previously merged in #375 but in dark mode.
-  Closes #526 
Not relevent
No

Fix: Dark theme footer style

---

components/Code.tsx
components/Layout.tsx
components/Sidebar.tsx
context.ts
pages/blog/index.page.tsx
pages/blog/posts/manfred-case-study-es.md
pages/implementations/index.page.tsx
pages/index.page.tsx
tailwind.config.js

Getting back the lost changes from the pr #365 
Fixed landing page, blog page, implementations page, blog markdown file and components for documentation page 
-  Closes #528 
N/A
**Summary**
Lost changes from previous PRs are now back
N/A

Fix: Getting back the lost changes from PR  #365

---

components/Sidebar.tsx

In the sidebar component specification links moved upper. As it was required to move to the below overview, I did so.
-  Closes #541  
-  Others? 
**Summary**

Specification links in sidebar moved upper

---

components/Layout.tsx
components/StyledMarkdown.tsx
context.ts
pages/implementations/index.page.tsx
pages/implementations/main.md
pages/learn/getting-started-step-by-step.md

**Summary**
I am testing plausible events.

add plausible events to getting started

---

pages/blog/posts/[slug].page.tsx

A bugfix
#458 
Closes: #458 
**Summary**
Made CSS changes to the left container on blog post page to improve its appearance on scrolling the blog.
NO

Fixed the side bar of blog post page.

---

pages/understanding-json-schema/reference/combining.md

'A snippet of the British royal family tree' seems to be a line that has been copied twice here but is irrelevant here.
in ```pages/understanding-json-schema/reference/combining.md```
doc bug fix
-  Closes #564 
**Summary**

fix: remove unnecessary lines

---

.github/workflows/greet_on_first_merge.yml
.github/workflows/new-implementation.yml

-  Closes #539  
**Summary**
- Updated the actions/github-script to v7 , which is the latest version using Node.js 20.
No

Bug/Maintenance: Updating actions to use Node.js 20

---

pages/index.page.tsx

This PR reviews the sponsors as they current status in Open Collective.

Review of the sponsors section

---

components/StyledMarkdown.tsx

Ensures dark mode compatibility
-  Closes #587 

Added the dark mode compatibility

---

components/Sidebar.tsx

Bugfix
-  Closes #596
Before
https://github.com/json-schema-org/website/assets/96608169/8c3d5ade-147b-4544-9314-f0d2e6262292
After
https://github.com/json-schema-org/website/assets/96608169/3611db39-4f6f-4a76-a7b9-99f44708760f
No

Fixed sidebar navigation arrow

---

components/Sidebar.tsx

Closes #606
**Summary**
Added a hover effect on drop down icon present in Side Navbar in docs section by making required CSS changes.
No

Adding hover effect to Side Navbar.

---

pages/learn/getting-started-step-by-step.md
pages/specification.md

Bugfix
-  Closes #462 
- #463
https://github.com/json-schema-org/website/assets/96608169/d944fcb2-31b0-4d09-b358-3f046230eff5
https://github.com/json-schema-org/website/assets/96608169/b491c2a6-3c27-413d-a1e1-50420b061b26
No
**Summary**
I have thoroughly checked if there is any conflicting uri/anchor tag/link, and as I have added a new anchor tag there will be no issue with backwards compatibility.
No

Fixed smooth scroll for specified links

---

pages/index.page.tsx

Improving the sponsors area of the landing page to differentiate each sponsorship layer and also adding buttons to become a sponsor.
-  Closes #602 
**Summary**
This enhancement introduces new design for the SPONSORS section of the page, that differentiated sponsors in GOLD, SILVER and BRONZE category . It also introduces an button :-
"Add your logo here " 
No

Improving Sponsors area 

---

pages/index.page.tsx

Improve links in sponsors section of landing page.

Sponsors links

---

public/_redirects

Add redirect from tools to implementations
-  Others? 
**Summary**

Add redirect from tools to implementations

---

components/StyledMarkdown.tsx

Bugfix
-  Closes #592
issue:
https://github.com/json-schema-org/website/assets/96608169/74a9cdfc-53fb-48d7-a4ac-a2c8e48e28f2
fix:
https://github.com/json-schema-org/website/assets/96608169/0314faec-6229-4460-8bf5-1290f9f22ca6
No

Fixes: all invisible table headers

---

components/DocsHelp.tsx

This modifies the feedback response now it says :
Thanks for the feedback! See it on [#website](https://json-schema.slack.com/archives/C8C4UBXDF) in [Slack ](https://json-schema.org/slack)for further discussion.
-  Closes #561 
**Summary**
It improves feedback response for better user experience.
No it doesn't.

Added #website and slack link to feedback

---

pages/index.page.tsx

This PR centers the buttons of community section and introduces padding .
-  Closes #599 
**Summary**
This PR solves the lack of proper spacing between the 
NO

Added padding and centered the buttons of Community section

---

components/Headlines.tsx

Highlight the active fragment heading so that users can know which one is currently active.
-  Closes #303 
Light Mode: 
Dark Mode:
**Summary**
Adding highlight feature to active headings. 
N/A

Feat: Highlighting fragment heading. 

---

components/Sidebar.tsx

1. Added dark mode consistency in the side panel when it is opened in mobile responsive mode.
**Before**
**After**
2. aligned panel header.
**before**
**after**
-  Closes #584

Feat: Making dark mode consistent and some bug fixes.

---

public/_redirects

New slack links

---

pages/index.page.tsx

The search button in the hero page was not fully clickable only the svg icon was clickable.
I have added a function to make the button fully clickable.
-  Closes #556 
https://github.com/json-schema-org/website/assets/119804372/3327fa6d-27dd-4a60-8bf8-29dea7d33c67
No

Search button in hero page functionality added 

---

pages/implementations/main.md

Very minor misspelling fix.
**Summary**
I was reading through the page, happened to notice the misspelling, and wanted to submit a PR to get it fixed :rocket: 
No.

docs: fix minor misspelling

---

pages/overview/code-of-conduct/index.page.tsx
pages/overview/sponsors/index.page.tsx

Add docs component to CoC and Sponsors
**Summary**

Add docs component to CoC and Sponsors

---

components/Sidebar.tsx

**Summary**
This PR adds the JSON Schema landscape to the sidebar
No, just a new link in the sidebar.

Add the landscape to the sidebar

---

.github/workflows/issue.yml

- Setup issue.yml file to consolidate all task actions related to issues.
- Combine both the first-time interaction message and the issue labeller into this file, so that we do not need to run two separate workflows when an issue is created.
-  Closes #692 
**Summary**

Feature: Added Issue-yml

---

components/Sidebar.tsx
data/resources.yml
pages/resources/[slug].page.tsx
public/icons/bookshelf-dark.svg
public/icons/bookshelf.svg

**GSoD'24 | web-release-3**
Moved resources section to new branch 
-  Related to #158 
N/A
N/A
**Summary**
N/A
N/A

WEB-R-3: Moving resources to new branch

---

components/StyledMarkdown.tsx

Redesigning the tableOfContent Component. 
-  Closes #571
**Light Mode**
**Dark Mode**
N/A
**Summary**
TableOfContent component design improvements. 
N/A

Feat: Table of content component design change 

---

.github/workflows/pull-request-target.yml

- Bug Fix : Fixes failing workflow `pull-request-target.yml`
-  Closes #712 
**Summary**

Fixes: failing workflow pull-request-target-yml

---

components/StyledMarkdown.tsx
pages/learn/getting-started-step-by-step.md

**Summary**
Improve table of contents for getting started guide
**Does this PR introduce a breaking change?** No

Improve table of contents for getting started guide

---

components/StyledMarkdown.tsx

**Summary**
change the table of content fonts from bold to medium
**Does this PR introduce a breaking change?** No

change the table of content fonts from bold to medium

---

components/Layout.tsx
components/SiteLayout.tsx
package.json

Removing Plausible provider from the project.  
N/A
N/A
N/A
**Summary**
Plauslibe provider removed.
N/A

feat: removing plausible provider from project

---

.github/workflows/stale.yml

**Summary**
This PR updates stale.yml to add another exempt label

Update stale.yml to add another exempt label

---

data/validator-libraries-modern.yml

More dialects coming soon for those commands!

Clarify that the Intelligence.AI JSON Schema CLI now supports Draft 6

---

.github/workflows/pull-request.yml

- Chore: updated unauthorized file detection jobs to not run when PR is from dependent[bot]
- There is no issue as this is just an improvement.
**Summary**

chore(unauthorized-file) : updated unauthorised file detection jobs

---

data/validator-libraries-modern.yml

Doing 2019-09 and later will take me a bit more! 😅

Clarify that the Intelligence.AI CLI now fully supports Draft 7

---

.github/workflows/links.yml

**Summary**
Update links.yml workflow to replace localhost with production domain.

Update links.yml workflow

---

public/_redirects

This PR creates a redirect to improve the Ambassadors Program url.

Add redirect to have a better ambassadors url

---

pages/blog/posts/json-schema-ambassadors.md

**Summary**
This PR introduces a better style for the quotes in the ambassadors blog post
No

Better style for the quotes in the ambassadors blog post

---

pages/overview/faq/index.page.tsx

**Summary**
Add the docs help document in the new FAQ page.
No

Add docs help component

---

components/StyledMarkdown.tsx
public/icons/toc-menu.svg
tsconfig.json

Refactored Table of content styles
-  Closes #784 #795
**Summary**
ToC component refactored

Feat: Refactoring toc styles

---

pages/understanding-json-schema/structuring.md

bugfix
https://json-schema.org/understanding-json-schema/structuring#bundling
**Summary**
Someone [reported](https://github.com/json-schema-org/website/commit/43dd3f9096942a5fca86cb06da22949671c8fcbc#r144600311) this bug that got introduced with a recent change.
No

Fix bundling docs bug

---

data/validator-libraries-modern.yml

Clarify that the Intelligence.AI CLI fully supports 2019-09

---

pages/implementations/main.md

Adds [jsonschema-markdown](https://github.com/elisiariocouto/jsonschema-markdown) to the list of tools used for documentation.
N/A
N/A
Yes
**Summary**
Adds [jsonschema-markdown](https://github.com/elisiariocouto/jsonschema-markdown) to the list of tools used for documentation.
No

chore: Add jsonschema-markdown project to Documentation section.

---

components/Sidebar.tsx
pages/docs/index.page.tsx
pages/index.page.tsx
pages/learn/index.page.tsx

**Summary**
This PR adds Tour of JSON Schema to the website by:
- Add the tour to the getting started section.
- Creating a new landing page for the getting started section with the links for the getting started guide or the tour.
- The getting started button of the landing page now redirects to the new getting started landing with a button to access the tour.
**Does this PR introduce a breaking change?** No

Adding Tour of JSON Schema to the website

---

data/validator-libraries-modern.yml

Updating my implementation information (dev.harrel)

dev.harrel impl: update info

---

components/Accordion.tsx
components/Code.tsx
components/DarkModeToggle.tsx
components/DocsHelp.tsx
components/Headlines.tsx
components/JsonEditor.tsx
components/Remember.tsx
components/ScrollButton.tsx
components/jsonSchemaLinks.ts
cypress/components/Accordian.cy.tsx
cypress/components/Code.cy.tsx
cypress/components/DarkModeToggle.cy.tsx
cypress/components/DocsHelp.cy.tsx
cypress/components/Faq.cy.tsx
cypress/components/Headlines.cy.tsx
cypress/components/JsonEditor.cy.tsx
cypress/components/Remember.cy.tsx
cypress/components/ScrollButton.cy.tsx
cypress/plugins/mockNextRouterUtils.ts

Added Component test for:
- Accordian Component
- DarkModeToggle Component
- Code Component
- Faq Component
- Headlines Component
- DocsHelp Component
- JsonEditor Component
-  Related to  #806 
**Summary**

testing(component-testing) :  Add component test 

---

data/validator-libraries-modern.yml

Fixes #865
Bug Fix
Closes #865 
NA
NA
**Summary**
Enhances readability and maintains integrity of the page by incorporating appropriate separations between different sections
NA

(Fixed) Some implementation descriptions are not clearly separated

---

data/validator-libraries-modern.yml

adding an implementation
n/a
n/a
Yes
**Summary**
Adds [v8r](https://github.com/chris48s/v8r) to list of command line tools.
Nope

add v8r to command line tools

---

data/tooling-data.yaml

This PR adds JS support for Quicktype.io 
-  Others? 
**Summary**

Add JS support for quicktype

---

pages/tools/components/Sidebar.tsx

This PR aims to fix the formatting of the tooling type filter dropdown list items.
-  Others? 
**Summary**

[tools]: Fix tooling type filter dropdown item format

---

pages/tools/index.page.tsx

This PR aims to fix the unsorted dropdown items in the filters sidebar to be sorted alphabetically.
-  Others? 
**Summary**

[tools]: Fix filter items sorting

---

data/tooling-data.schema.json
data/tooling-data.yaml
lib/config.ts
pages/obsolete-implementations/index.page.tsx
pages/tools/JSONSchemaTool.ts
pages/tools/hooks/useToolsTransform.tsx
pages/tools/index.page.tsx

This PR aims to define and manage all tooling dialect drafts as String. In addition, it fixes an unexpected behavior when showing the supported dialect as dialect "0" appeared in the last position but it should appear in the first position.
Closes #924 
**Summary**

[tools]: fix tooling page dialects definition and sorting

---

pages/index.page.tsx

This PR fixes a formatting issue in master branch that breaking the Cloudflare deployments.

Fix formatting issue in master branch

---

components/Sidebar.tsx
public/icons/external-link-black.svg

Fixes #942
Enhancement
-  Closes #942 
**Summary**
Added an external link icon to differentiate between External Links and Internal Links

(Enhancement) Differenciate external links in the docs sidebar

---

components/GettingStarted.tsx
pages/learn/getting-started-step-by-step/getting-started-step-by-step.md
pages/learn/getting-started-step-by-step/next-steps.md

**Summary**
This PR removes the plausible events we declared to track the user activation flow. We are doing this now to reduce costs considering nobody is actively working on refining that funnel.
No.

Remove plausible events to reduce costs

---

data/tooling-data.yaml

Update info about my validator library

Update json-sKema project info

---

pages/docs/index.page.tsx

- Fixes the 404 error incurred when attempting to contribute to the main docs page
-  Closes #1012
**Summary**
- Fixed 404 on contribute to this page button on /docs/

Fix: 404 on main docs page

---

data/tooling-data.schema.json
data/tooling-data.yaml

- Adding [JSONSchema.jl](https://github.com/fredo-dedup/JSONSchema.jl) for [Julia](https://julialang.org/) to the tools

add JSONSchema.jl to tooling page

---

CONTRIBUTING-docs.md
CONTRIBUTING.md

**Summary**
This PR fixed the deployment error after merging #1013.

Fix the links of contributing guide after merging #1013

---

next-env.d.ts
pages/index.page.tsx

fix the horizontal overflow. YOUR LOGO HERE button is being overflow causing horizontal overflowing in the whole page
-  fix
#1044 
https://github.com/user-attachments/assets/43b2c0aa-48d2-47bd-8bac-d3fd0ea1dc03
No
**Summary**
No

Responsive issue #1044

---

data/keywords.yml

Edit keywords to camelCasing
Issue #1062 

Edit keywords to camelCasing

---

data/tooling-data.yaml

- Adding [svelte-jsonschema-form](https://github.com/x0k/svelte-jsonschema-form) to the tools

Add svelte-jsonschema-form to tooling page

---

INSTALLATION.md

-  Others - Added a one line disclaimer that environment variables are optional to run the code on local machine.
**Summary**

Added a one line disclaimer that environment variables are optional to run the code on local machine.

---

pages/md-style-guide.md

It adds a link to the 'Docs contributing guide' and corrects some errors in the 'Titles and headings' section
-  Others? 
**Summary**
This PR introduces the following changes:
- Adds a link to the 'Docs contributing guide' 
- Corrects some errors in the guidelines provided for writing titles and headings. 

Add a link to the 'Docs contributing guide'

---

pages/overview/what-is-jsonschema.md

bugfix
As per the [discussion](https://json-schema.slack.com/archives/CB3SS5W5B/p1730440533328929) in `#documentation` channel it was specified NOT to open a new issue. 
Before:
After:
**Summary**
Removes the extra colons (typos) in [What is JSON Schema](https://json-schema.org/overview/what-is-jsonschema)
No

Fix remove extra colons in what-is-jsonschema.md

---

pages/blog/posts/website-analytics-snapshot-2023.md

**Summary**
Neptune representatives reached out asking to add their url to the Neptune reference. We are just adding it.

Update website-analytics-snapshot-2023.md to add neptune link

---

pages/draft-06/index.md

-> Draft-06 broken link fixed
-  Closes #1191
N/A
**Summary**
Draft-06 broken link is now fixed
N/A

Fix: draft-06 broken link fixed

---

components/DocTable.tsx

-  Closes #1030 
https://github.com/user-attachments/assets/0094a452-7eda-4e5a-a15f-78f458ef28ce

improve Specification page design

---

styles/globals.css

Bug FIx : Search Icon background bug 
-  Closes #1214 
-  Related to #1214
-  Others? Nothing
Dark ->
Light->
N/A
**Summary**
N/A Just Solved bug

fixed SearchIcon background bug

---

components/Sidebar.tsx

The transition effect for expanding and collapsing the Specification dropdown is working fine now
-  Closes #1335  
https://github.com/user-attachments/assets/956f07ce-9ee7-4d93-9fad-e0d47031b089
**Summary**
No

Bug : solve the dropdown issue

---

pages/community/index.page.tsx

Adding loading, priority, and quality configurations to next image component to optimise increasing the image loading time of community page avatar images.
-  Closes #1388
N/A
N/A
**Summary**
community page avatar images are optimised 
N/A

Fix: community page avatars loading optimised

---

data/tooling-data.yaml

This PR updates information about an existing implementation.
Please, let me know if something else is also required to update the information. Thank you!

Update information about Kotlin json-schema-validator

---

components/Sidebar.tsx

Removed conflicting css property from Sidebar.tsx component.
-  Closes #1417 
Below is screenshot after resolving the conflicting CSS.
No
No

fix: removed conflicting css property

---

data/use-cases.json
pages/overview/use-cases/index.page.tsx

This PR will fix the issue where a link would stick out of the card in issue #1445, and will the adjust page to mobile as part of the issue #1464
-  Closes #1445 
-  Related to #1464 
for mobile :
for desktop:
**Summary**
I adjusted the link to appear as a word instead of a URL and optimized the page for mobile.
no

Adjusting the use cases page

---

INSTALLATION.md

bugfix
Closes #1217 
[Screencast from 2025-03-15 06-19-45.webm](https://github.com/user-attachments/assets/73bc1d04-8f7c-4417-99a5-6270a6fbf62c)
**Summary**
Fix the broken link in Installation.md 
No

Fix the broken link of docker in Installation.md

---

pages/learn/getting-started-step-by-step/getting-started-step-by-step.md

Makes a grammatical correction to a phrase.
Copy edit.
-  Others? 
This is a correction in documentation.
**Summary**
Grammatical correction.
No.

fix: make grammatical correction

---

pages/404.page.tsx

enhancement
-  Closes #1082 
---
**Summary**
- Designed and implemented the 404 page taking inspirations from [this mockup](https://github.com/json-schema-org/website/issues/1082#issuecomment-2453317342).
No

enhancement: new 404 page

---

pages/index.page.tsx

Bugfix: Fixes a 404 error when clicking the "pro services" link on the homepage
-  Closes #1522  
-  Others? 
Before fix:
When clicking on "pro services" link on the homepage, users encounter a 404 error page because the link points to /pro-help which doesn't exist
https://github.com/user-attachments/assets/debe93fb-15eb-418f-baa9-45c0eddd8ddf
After fix:
The link now correctly points to /overview/pro-help where the page actually exists
https://github.com/user-attachments/assets/6c68729d-0efc-41d2-954a-0f571c39965f
**Summary**
This PR fixes a 404 error that occurs when users click on the "pro services" link on the homepage. The …

Bugfix: Fixes a 404 error when clicking the "pro services" link on the homepage

---

pages/community/index.page.tsx

Center button and text inside cards on the Community page cards.
-  Closes #1493
**Summary**
This PR centers the button and text inside the cards on the Community page, improving the visual presentation.
no

improving the community page by adjusting the card text and buttons placement

---

components/Layout.tsx

This PR changes the active state of tools page.
-  Closes #1375 
before
after

Fixes active navbar

---

data/tooling-data.yaml

feature
- Closes #1702 
**Summary**
This PR adds a reference to https://github.com/Cosium/json-schema-to-java-record to the documentation.
No

Reference https://github.com/Cosium/json-schema-to-java-record

---

pages/blog/index.page.tsx

Enhancement (performance): adds loading, priority, and quality settings to all blog images.
-  Closes #1404 
N/A
N/A
**Summary**
N/A

feat: optimize blog image loading wit priority, lazy and quality
