json-schema-org/website

data/validator-libraries-modern.yml, pages/implementations/main.md
Adds OpenAPI JSON Schema Generator Implementation
The project implements the majority of the draft 2020-12 json schema keywords per [the latest release](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/releases/tag/3.1.0) which runs the json schema test suite for verification
=> Adds OpenAPI JSON Schema Generator Implementation

components/Sidebar.tsx, context.ts, pages/implementers/[slug].page.tsx, pages/implementers/interfaces.md, pages/learn/interfaces.md
This page doesn't yet compile even, failing with some obscure Javascript error in a headline.
It was however ported from a reST page, so I'm still figuring out what flavor of markdown is needed to work with the site.
Marking it as [WIP] at least until I figure out what needs tweaking -- which certainly seems likely to be at least the `topic` and `glossary` bits, as Markdown doesn't really have equivalents of these, so I assume some Javascripting is necessary to implement something similar to the Bowtie page.
But the content is ready for immediate review.
=> Add an initial version of a page on common interfaces.

components/StyledMarkdown.tsx
Use dark style for code blocks for consistency with json blocks.
=> Use dark style for code blocks

pages/index.page.tsx
Better location of the slack logo to make it easier to join slack in the landing page
=> Better location of the slack logo to make it easier to join slack in the landing page

public/draft/2020-12/draft-bhutton-json-schema-01.html, public/draft/2020-12/draft-bhutton-json-schema-validation-01.html, public/draft/2020-12/relative-json-pointer.html
Alternately (pun intended), I could create links to the actual XML documents. This is easier and I think it's sufficient.
=> Remove rel=alternate links that 404

.github/workflows/new-implementation.yml
This workflow will comment on PRs that add new tools / implementations to the website. It will do so only on PR open (i.e. once), not whenever the PR is modified.
The goal is to direct implementers (or users submitting on their behalf) to review some resources that might be applicable to them.
We can of course grow or shrink this list as needed, if we wish to point to additional resources.
Right now, the way it detects which PRs are tool additions is by considering any PR which touches:
* the YAML files in the data directory
* the pages/implementations/main.md page
to be possible candidates.
Additional tweaks could be made to add or remove these triggers if the commenter is too noisy, or not noisy enough.
For PRs which touch these pages, this looks like:
PRs which do not meet the above …
=> Add an automatic commenter for new tooling PRs.

pages/implementations/intro.md, pages/learn/glossary.md, pages/obsolete-implementations/intro.md
Fixes a few 404s, specifically on the Glossary page.
This does not update the pages/blog/posts/website-analytics-snapshot-2023.md 2023 blog post (which directly links to the json-schema-org.github.io source repository and references behavior that isn't the case for the new website). json-schema-org/community#514 is relevant here, and should likely consider what to do with this link and blog text as part of that PR.
This also does not touch files in the _include directory, which are submodules included from the spec repo and will have their own PR there.
=> Update the links on a few pages to point to the new website repo.

pages/specification-links.md
Fix broken link in specifications links page because of a missing parenthesis
=> Fix broken link because of a missing parenthesis

.github/workflows/new-implementation.yml
This doesn't *seem* like it should matter -- in that this workflow was tested as-is on a different repository as part of building it, and ran successfully. Furthermore, the docs for the permissions property in GitHub (at https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) say:
You can use permissions either as a top-level key, to apply to all
jobs in the workflow, or within specific jobs. When you add the
permissions key within a specific job, all actions and run commands
within that job that use the GITHUB_TOKEN gain the access rights you
specify.
so, top-level seems like it's supposed to work fine.
And yet, in the "Set up job" step of #206, the permissions for PullRequest are shown as:
PullRequest: read …
=> Try tweaking the permissions on the token for the autocommenter.

pages/implementations/main.md
Support for Draft 2020-12 in the `victools`:`jsonschema-generator` library was introduced end of 2021; support for Draft 6 even before that.
Merely updating the reference here.
=> chore: Update supported draft versions for Java Generator from code

.github/workflows/new-implementation.yml
See the warning at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
Specifically, without using the pull_request_target event, this (not running) is intended behavior for security reasons.
Now it *should* actually run from forks (*crosses fingers*).
=> Again fix the autocommenter to run, now on forks.

pages/implementations/main.md
Hey, it was suggested on [Slack](https://json-schema.slack.com/archives/C5CF75URH/p1697889828358549), that I raise a PR to add a link to the implementations page for a new performance benchmark & functionality comparison microsite we've created while trying to decide which JVM based validator implementation to use.
Site: https://www.creekservice.org/json-schema-validation-comparison/
Repo: https://github.com/creek-service/json-schema-validation-comparison
The site is designed to be auto-updating, via GitHub dependabot, as new versions of implementations are released. Contribution from implementation developers is encouraged.
=> Add a link to new JVM validator benchmark

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/enhancement.md
**Summary**: Add comments in the issue templates to avoid people not removing the template suggestions.
No
=> Comments in templates

pages/index.page.tsx
Replace old contact email ben@jsonschema.dev with info@json-schema.org.
=> Replace the contact email with info@json-schema.org

pages/understanding-json-schema/reference/numeric.md
**Summary**:
Change `valid` to false, as the title said, "Numbers as strings are rejected"
Yes/No
=> fix(numeric): fix wrong sample

public/_headers
=> Add custom headers for meta-schemas

pages/implementations/main.md
Hello :)
I didn't found a fitting pre-existing place for this Markdown oriented tool, so I've added an additional sub-section in "Utilities".
It works inside remark + remark-lint, so technically it's a **lint rule**, but also an IDE / pipeline runtime **validator** at the same time… 🤔
Tell me if it's looking good for you ;)
And, again, thanks for all the work you're putting up!
=> Add `remark-lint-frontmatter-schema` to "Linters" implementations

data/validator-libraries-modern.yml
Hello, recently I created my personal project about json schema implementation for .net. It is based on draft 2020-12, has known limitation currently listed in project doc but it also has some features and advantages. Currently it is a free close source project and may be transferred to be open source in future.
I am not sure if it is proper to be added to this website's implementation list. The description of implementation: https://github.com/lateapexearlyspeed/Lateapexearlyspeed.JsonSchema.Doc
Intention of writing this implementation:
Several years ago, I touched and learned json schema concept during work, and feel json schema is interesting concept because it can describe any data well, and I used some excellent json schema libraries for work. Years later, I would like to implement …
=> Apply for adding new json schema validator implementation for .Net: LateApexEarlySpeed.Json.Schema

pages/blog/posts/apidays-paris-2023-recap.md
**Summary**: Fix mobile view if the APIDays blog post
No
=> Fix mobile view if the APIDays blog post

pages/implementations/main.md
**GitHub Issue:** NA
**Summary**:
This PR adds [eslint-plugin-json-schema-validator] to the list of **Linter plugins**.
[eslint-plugin-json-schema-validator] is an ESLint plugin that validates code using JSON schema and reports violations.
[eslint-plugin-json-schema-validator]: https://github.com/ota-meshi/eslint-plugin-json-schema-validator/
---
close https://github.com/ota-meshi/eslint-plugin-json-schema-validator/issues/281
=> Add eslint-plugin-json-schema-validator to "Linter plugins" implementations

pages/implementations/index.page.tsx
**GitHub Issue:** #270 
**Summary**: Fix to include the missing compliance notes of the validators in the implementations page.
No
=> Fix to include compliance notes of the validators

components/StyledMarkdown.tsx
**Summary**: Currently the text using _ format text as Italic is not working. The expected behaviour of the website is to render _text_ to <i>text</i>.
No
=> Add support for the Markdown convention for Italic text using _

components/DocsHelp.tsx
Correct link to start a new Q&A discussion
**GitHub Issue:** NA
**Summary**:
Fixing a slightly broken link in the docs. Most of the redirects from `github.com/json-schema-org/community/` to `github.com/orgs/json-schema-org` work correctly (eg - [https://github.com/_**json-schema-org/community**_/discussions/34](https://github.com/json-schema-org/community/discussions/34) correctly redirects to [https://github.com/_**orgs/json-schema-org**_/discussions/34](https://github.com/orgs/json-schema-org/discussions/34)), but this link to start a new Q&A discussion doesn't.
When clicked, it takes you to https://github.com/orgs/json-schema-org/discussions/new/choose with the following error banner:
This PR updates that link in the help popup, to point directly to `orgs/json-schema-org`.
**Do you …
=> Correct Q&A discussion link in DocsHelp.tsx

.idea/vcs.xml, data/validator-libraries-modern.yml, pages/implementations/main.md
**Summary**:
Updates openapi json schema generator
- lists the project in java + python for validation
- lists the project in java and python for code generation, adds json schema drafts
I am updating these sections because I am the maintainer of that project and I [recently added draft 2020-12 schema validation to the java code generator](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/releases/tag/4.1.0).
Yes/No
=> Updates openapi json schema generator

data/validator-libraries-modern.yml
As of 1.3.1 the networknt/json-schema-validator supports 2020-12 and 2019-09.
- https://www.creekservice.org/json-schema-validation-comparison/functional#summary-results-table
=> Update networknt/json schema validator to indicate support for 2020-12 and 2019-09

data/validator-libraries-modern.yml
The .net implementation of json schema: LateApexEarlySpeed.Json.Schema turns to be open-source now, so I would update link from previous doc repo to current open source project repo. Thanks !
=> Update implementation link to open source project repo

pages/learn/glossary.md
**GitHub Issue:**
Resolves https://github.com/json-schema-org/json-schema-spec/issues/1440
**Summary**:
Adds a glossary entry for 'implementation' as discussed in the issue above.
No
=> add glossary entry for 'implementation'

pages/implementations/main.md
**GitHub Issue:** NA
**Summary**:
Web UI generation - Add [json-schema-form](https://github.com/remoteoss/json-schema-form) by @remoteoss
No, because It's not a core change to the website. It's just adding a new OSS tool to the existing Implementations list.
=> chore(implementations): Web UI generation - Add json-schema-form by Remote.com

CONTRIBUTING.md
**Summary**: Add the new triage process to contributing
No
=> Add triage to contributing

pages/understanding-json-schema/reference/type.md
**Summary**:
Some of the markdown tables in the [reference guide for types](https://json-schema.org/understanding-json-schema/reference/type) are broken. In particular, both Objective-C and Swift. That ends up being rendered wrongly:
This PR fixes both tables and also reformats the others so they all follow the same format.
=> docs: fix type reference markdown tables

components/Layout.tsx
**GitHub Issue:** #328
**Summary**:
I have made the styling of elements in header consistent.
Earlier:
Corrected:
No
=> Fixed header spacing in mobile view

components/JsonEditor.tsx, public/icons/copied.svg, public/icons/copy.svg
**GitHub Issue:** Resolves https://github.com/json-schema-org/website/issues/344
**Summary**:
The previous copy code button covered the validity indicator. This PR changes it to a copy icon next to the data type label.
**Before:**
**After:**
**New click animation:**
https://github.com/json-schema-org/website/assets/46278840/740b895f-8e5c-49f7-beca-75b6d3db9485
<hr>
**Implementation notes:**
Both the icons are always rendered with one always being invisible. I tried to use a ternary operator, but the hover animation caused the copy icon to flash after coming back, and I didn't like the way that looked:
https://github.com/json-schema-org/website/assets/46278840/c37d11ed-a33c-47bb-9493-51bedea88a84
**Do you think resolving this issue might require an [Architectural Decision Record …
=> Change copy code button to an icon

components/Layout.tsx, context.ts, pages/implementations/index.page.tsx, pages/obsolete-implementations/index.page.tsx
**GitHub Issue:** #320 
Resolves: #320
**Summary**: This PR renames the Implementations section in favour of Tools
No
=> Rename implementations section to tools

pages/draft/2020-12/release-notes.md
**GitHub Issue:** #360  
**Summary**: Replaced the usage of the `"type"` keyword by `"$ref"` in 4 places where the value of `"type"` was clearly describing a reference.
no
=> fix typo: type -> $ref

styles/globals.css
**GitHub Issue:** #302 
**Summary**: Fixed the obscuring of heading on fragment link click
No
=> Add smooth scrolling and scroll padding to HTML

pages/_document.page.tsx
**GitHub Issue:** #363  
Closes #363 
**Summary**:
Fixed the problem of extra width on the pages which was causing horizontal scroll ruler to appear 
https://github.com/json-schema-org/website/assets/115284013/99e950e8-16cd-4f54-a8a0-228c628d942a
**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)** 
No
=> fix: #363 extra width on the pages

pages/index.page.tsx
In this issue, I addressed a bug related to icon sizes. I observed that the Slack icon had a larger height compared to the common room icon. To rectify this issue, I applied a scaling property to ensure uniform icon sizes.
This enhancement is crucial for maintaining a visually consistent and polished appearance across the platform. The "before" and "after" screenshots provide a clear visual representation of the improvement.
**GitHub Issue:**  #366 
Closes #366 
**Summary**:
before :
after :
=> fix: #366  Resolve the icon size bug under the "Supported by" section

components/Layout.tsx
**GitHub Issue:** #396 
**Summary**: Changed the /tools route to /implementations in MobileNav. 
Since Tools tab is addressed by /implementations route /tools route is still not found. But if required i can redirect the /tools route to /implementations so that it is does not give 404.
No
=> changed the /tools route to /implementations in MobileNav

components/Layout.tsx
**GitHub Issue:** We found a build error in cloudflare after the last merge.
````
10:51:22.519 | Failed to compile.
-- | --
10:51:22.519 |  
10:51:22.519 | ./components/Layout.tsx
10:51:22.519 | 94:1  Error: Expected indentation of 4 spaces but found 6.  indent
10:51:22.520 |  
10:51:22.520 | info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
10:51:22.531 | Failed: build command exited with code: 1
10:51:23.318 | Failed: error occurred while running build command
````
=> Fix eslint warning

pages/blog/index.page.tsx
This fixes this:
````
14:17:08.158 | Failed to compile.
-- | --
14:17:08.158 |  
14:17:08.158 | ./pages/blog/index.page.tsx
14:17:08.159 | 17:40  Error: 'params' is defined but never used.  @typescript-eslint/no-unused-vars
14:17:08.159 | 17:53  Error: A space is required before '}'.  object-curly-spacing
14:17:08.159 | 17:55  Error: Unexpected space before the ':'.  @typescript-eslint/type-annotation-spacing
14:17:08.159 | 18:18  Error: Unexpected separator (,).  @typescript-eslint/member-delimiter-style
14:17:08.160 | 36:49  Error: Extra semicolon.  semi
14:17:08.160 | 47:99  Error: Extra semicolon.  semi
14:17:08.160 | 53:86  Error: Operator '\|\|' must be spaced.  space-infix-ops
14:17:08.160 | 56:29  Error: Extra semicolon.  semi
14:17:08.160 | 58:38  Error: Extra semicolon.  semi …
```
=> We found some issues in cloudflare in the last deployment

pages/specification-links.md
**GitHub Issue:** #123
Resolves #123 
**Summary**:
- added published/release dates for each versions (e.g. draft 6, draft 7) 
**Files Changes**
- `pages/specification-links.md`
**Before**
Can see on website [here](https://json-schema.org/specification-links#2020-12)
**After**
[screen-recording.webm](https://github.com/json-schema-org/website/assets/84331681/c15e08ce-aa80-4540-871b-a9e39b397801)
Yes/No
No
=> added dates to specification link

components/Layout.tsx
GitHub Issue: #398 
Resolves #398 
Summary: Update search box location on mobiles
Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)
Yes/No
No
=> fix: #398 Search box of header misplaced for certain mobiles

pages/index.page.tsx
After the last merge to main we found these issues in cloudflare:
````
12:27:34.833 | Failed to compile.
12:27:34.834 |  
12:27:34.834 | ./pages/index.page.tsx
12:27:34.834 | 295:1  Error: Delete `········`  prettier/prettier
12:27:34.834 | 296:1  Error: Delete `·`  prettier/prettier
12:27:34.834 | 296:1  Error: Expected indentation of 8 spaces but found 9.  indent
12:27:34.834 | 297:1  Error: Insert `·`  prettier/prettier
12:27:34.835 | 297:1  Error: Expected indentation of 10 spaces but found 9.  indent
12:27:34.835 | 487:1  Error: Delete `············`  prettier/prettier
12:27:34.835
````
This PR intends to fix that.
=> Prettier issues after the last merge to main

public/_redirects
Related #161 
After merging #406 we found that redirects didn't worked.
We think it may be because we need to add the redirect in the file next.config.js and that file generate the _redirect.
https://github.com/varanauskas/nexered?tab=readme-ov-file#supported-providers
=> Fix redirects

components/CarbonsAds.tsx
Removing a bug related to carbon ads
-  Closes #457  
Before: Once the ad is loaded , changes in screen orientation would result in uneven placing of the carbon ad.
After: When the screen orientation changes, the ad is removed even after being loaded and not resulting into uneven ad placing. 
no
**Summary**
Made changes  to make sure that ads can be removed automatically if required even after being loaded that is when screen orientation changes from landscape to vertical to use as much screen for the content.
no
=> removing carbon ads accordingly when screen oreintation changes

pages/learn/getting-started-step-by-step.md
Earlier the code blocks which are in continuation was not showing the aspected colors which is now fixed by converting `json` to `jsonc` code blocks.
-  Closes #349   
- Before
- After
Not required in this but if needed I will.
**Summary**
replaced `json` with `jsonc` at relevant places  
N/A
=> Fix: Fixing Inconsistent code rendering.

pages/understanding-json-schema/basics.md, pages/understanding-json-schema/structuring.md
Fix broken link to `"$id"` keyword.
- [https://json-schema.org/understanding-json-schema/basics#declaring-a-unique-identifier](https://json-schema.org/understanding-json-schema/basics#declaring-a-unique-identifier):
- [https://json-schema.org/understanding-json-schema/structuring#structuring-a-complex-schema](https://json-schema.org/understanding-json-schema/structuring#structuring-a-complex-schema):
- [https://json-schema.org/understanding-json-schema/structuring#id]( https://json-schema.org/understanding-json-schema/structuring#id):
**Summary**
Stumbled upon it while reading.
=> chore: fix broken link to "$id" keyword

components/StyledMarkdown.tsx, pages/draft/2020-12/release-notes.md
-  Closes #483  #487  
-  Others? 
**Before**
https://github.com/json-schema-org/website/assets/94185167/5a59b99d-f71f-4855-814e-6cbf271dff91
**After**
https://github.com/json-schema-org/website/assets/94185167/9a33a0ff-bf5a-471f-aeb6-df5fd49d8c7a
**Summary**
1- Here I have fixed the behavior of the table before it was taking full width and there was not any overflow or width property.
2- I have also made changes in the release-notes.md, which was causing a hydration error and  I made a change at line number 466. it was taking more than required width.
- No
=> Fix: draft behaviour and hydration error

components/Layout.tsx, components/Sidebar.tsx
remove the mx-auto form sidebar because we have mx-4 and mx-auto both in same line. and fix the footer space issue.
-  Closes ##455 
-  Others? 
**Summary**
=> fixed the footer space issue

components/Card.tsx
- **Enhancement**
- **Closes #433**
- Related to #426, #421 (These issues highlight the need for a standard card component)
https://github.com/json-schema-org/website/assets/70345027/efe5f5e1-2379-43c6-af78-69f5b949a363
- No documentation was added. But this is a short usage guide
- NB: icon and link are optional
```
import Card from 'components/Card';
// Example usage
<Card 
title="Card Title"
body="This is the card body content."
icon="path/to/icon.svg"
link="/link/to/page"
image="/link/to/image.svg"
/>
```
**Summary**
This pull request introduces a new reusable `Card` component for displaying list items in a standardized format. This component …
=> Standardize List Display with Card Component (#433)

components/Layout.tsx
**Changes Made:**
Smoothly scroll to the top onclick of the Search button to address the issue where clicking on the search button made the scroll unresponsive on devices with a width less than 769 pixels.
- Related to #478 
[Screencast from 09-03-24 06:43:46 PM IST.webm](https://github.com/json-schema-org/website/assets/106718914/ea17bb2a-6e64-4d61-aa7e-bb256d50a724)
**Summary:**
This pull request fixes the UI bug on devices with a width less than 770 pixels. The issue was causing the scroll to become unresponsive when clicking on the search button. Refer to the linked issue for more information.
=> Auto smooth scroll to the top onclick of the Search

components/Layout.tsx
While opening the search bar an overflow was visible in the right direction. Now the content will be at it's position on opening and closing of the search bar.
-  Closes #525  
https://github.com/json-schema-org/website/assets/119804372/4435b439-029a-4e49-88ea-94b7e401941e
No
=> handled the overflow issue while opening search bar

components/Accordion.tsx, components/Faq.tsx, components/Sidebar.tsx, data/faq.json, pages/overview/faq/index.page.tsx
**Issue Number:**#190
-  Closes #___ #190
-  Related to #___ [](https://github.com/json-schema-org/website/pull/429)
-  Others? 
**Summary**
=> feat: added Faq section

pages/understanding-json-schema/reference/object.md
This PR fixes two broken relative links:
* The link definitions used hyphenated anchors (like `"additional-properties"`)
* The target headers define non-hyphenated IDs (like `"additionalproperties"`)
You can see the current problem by visiting:
https://json-schema.org/understanding-json-schema/reference/object#properties
and attempting to click on the "Additional Properties" and "Unevaluated Properties" link in the call-out text.
`git blame` showed that the hyphenated anchor lines were modified a few months ago, while the target lines were last modified ~2 years ago, so I removed the hyphens to align with the long-standing target lines.
=> Fix broken links to header anchors

styles/globals.css
Bugfix, introduced after merger of dark mode
-  Closes #593
Before:
https://github.com/json-schema-org/website/assets/96608169/8d8392ae-c190-4d9c-bf0c-ba7c514f2e03
After:
https://github.com/json-schema-org/website/assets/96608169/f890b5ec-7555-4d2c-9f1d-14e0e1f24e68
No
=> fixes #593: Enabled smooth scroll behavior

components/StyledMarkdown.tsx
**Context:**
In a previous [PR](https://github.com/json-schema-org/website/pull/548/files#diff-bce1f7ae49066ac1a2d9d4786bce5a1e5080a05568ebc17a6d70cc62c16766c4), some console log statements were added unintentionally which are spamming the dev console rendering the console unusable during development and testing. This is also reproduced inside the server side console i.e. IDE terminal. 
This PR aims to resolve this by simply removing these unintentional console log statements.
-  Others? This PR does not link to any existing issue and follows up to the discussion on Slack.
=> [components][StyledMarkdown]: Fix unnecessary console log statements

.eslintrc.js, components/Layout.tsx
-  Closes #536
https://github.com/json-schema-org/website/assets/91591901/27750533-fefd-4525-b074-1a0172ea470a
No
**Summary**
No
=> Fix: navbar should close when user click anywhere on screen

pages/understanding-json-schema/structuring.md
Bug fix (indentation correction)
N/A
N/A
https://json-schema.org/understanding-json-schema/structuring
**Summary**
I was reading the [structuring doc](https://json-schema.org/understanding-json-schema/structuring) and found the indentation in a couple of the code examples confusing. I've adjusted it to be more like other examples of the address schema in the doc, making easier to read.
I hope not!
=> Fix some inconsistent indentation

pages/understanding-json-schema/reference/array.md
Bugfix of render the draft specific info of [UJS arrays](https://json-schema.org/understanding-json-schema/reference/array#additionalitems).
-  Closes #231 
=> Improve draft info render for arrays-additional items

components/StyledMarkdown.tsx
1. Making dark mode consistent for tabsgroup.
2. Making dark mode consistent for thead.
3. Imporved gradient color. 
-  Closes #608 
**Before**
Tabsgroup
Thead
**After**
Tabsgroup
Thead
=> Feat: Making dark mode consistent for tabsgroup and thead

pages/blog/index.page.tsx
- This PR adds selection effect to the [blog](https://json-schema.org/blog) category tags and adds hover effect on the tags (for dark mode)
-  Closes #627 
Not relevant 
No
=> Add background color to the selected tag in blog page

components/DocsHelp.tsx, pages/[slug].page.tsx, pages/draft-05/[slug].page.tsx, pages/draft-06/[slug].page.tsx, pages/draft-07/[slug].page.tsx, pages/draft/2019-09/[slug].page.tsx, pages/draft/2020-12/[slug].page.tsx, pages/implementers/[slug].page.tsx, pages/implementers/index.page.tsx, pages/learn/[slug].page.tsx, pages/overview/[slug].page.tsx, pages/understanding-json-schema/[slug].page.tsx, pages/understanding-json-schema/index.page.tsx, pages/understanding-json-schema/reference/[slug].page.tsx, pages/understanding-json-schema/reference/index.page.tsx
This PR updates the button text message from Make a contribution to --> Edit this page on github.
And also updates the link so it would point to the website github page and points to the code of the page you clicked the button from.
-  Closes #128 
NO
**Summary**
This is just simple button update so it would say right thing and point to right link.
=> Updating to Edit this page on Github

pages/learn/getting-started-step-by-step.md
Fixes the ordered list Discrepancy observed on the [getting-started-step-by-step](https://json-schema.org/learn/getting-started-step-by-step#optional) as reported in the issue #653 
-  Closes #653 
**Screenshots of fix**
**Summary**
It was a markdown spacing issue. Found the fix here [markdown-continue-numbered-list](https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list) and applied. 
`Note` - This might need to be applied to other pages as well which has this problem.
No
CC - @benjagm @gregsdennis  @jviotti
=> Fix the ordered list discrepancy on getting started page

CONTRIBUTING.md
Update CONTRIBUTING to clarify the need to link PRs to issues
**Summary**
No.
=> Update CONTRIBUTING to clarify the need to link PRs to issues

.github/workflows/links.yml
- Feature : This PR introduces a workflow to validate broken links.
-  Closes #103  
-  Related to #297 
- Automatic issue created by workflows
**Summary**
- This workflow is intended to check for broken links periodically.
- It will inspect all external links for validity.
- Requests returning status codes 200, 201, 429, and 403 will be considered acceptable.
- If any broken links are identified, corresponding issues will be created.
=> Feature : Added linkChecker workflow

pages/learn/glossary.md
As discussed in the [issue](https://github.com/json-schema-org/website/issues/266). This PR adds two very similar sections to the [glossary](https://json-schema.org/learn/glossary) section.
-  Related to #266  
- 
**Summary**
This PR is a part of the individual PR's getting created for completing the `glossary `page.
no
=> Add validation result and JSON pointer in the glossary

data/validator-libraries-modern.yml
Feature
- Closes #___ 
- Related to #___ 
- Others?
N/A
Yes, the documentation is updated with new implementation details.
**Summary**
This PR introduces a new Go JSON Schema validator, `kaptinlin/jsonschema`, to the list of implementations on the JSON Schema website. This library supports JSON Schema Draft 2020-12, providing advanced features such as enhanced output formats and multilingual error messaging. The inclusion of this library expands the tools available for Go developers in the JSON Schema community, aligning with the site's aim to list tools that support at least one recent version of the specification.
**Does this PR introduce a …
=> Add kaptinlin/jsonschema to Go implementations

pages/implementations/main.md
Hi, recently .NET implementation 'Lateapexearlyspeed.Json.Schema' can also support output standard JSON schema based on functionalities of fluent builder pattern and generator from .net types, so not sure if it is possible to add it to 'Schema generator' page section ? thanks !
=> Update main.md to add new package to schema generator section

data/validator-libraries-modern.yml, pages/implementations/main.md
This updated the implementation for the openapi-json-schema-generator project
It adds Kotlin validation + code generation
Kotlin validation/generation was introduced here: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
-  Others? 
**Summary**
No
=> Update openapi json schema generator to list kotlin validation and generation

pages/blog/posts/validating-openapi-and-json-schema.md
I saw a [question](https://stackoverflow.com/questions/78424948/openapi-validator-that-supports-a-custom-dialect) on StackOverflow that asked about validating OpenAPI documents with a custom JSON Schema dialect. I pointed them toward this blog post that answers part of their question, but I realized there are some brief code examples that use an old version of `@hyperjump/json-schema`, so I wanted to update those examples.
=> Update "Validating OpenAPI and JSON Schema" post

components/StyledMarkdown.tsx
Fixing text size such that it matches rest of the page.
-  Closes #710 
N/A
**Summary**
Text size is now fixed.
=> Fix: Fixing text size in TableOfContent component

data/faq.json, pages/overview/faq/index.page.tsx
Documentation Enhancement
-  Closes #706 
-  Others? 
I also reviewed the general question texts, which are properly formatted and good to go.
No
=> improved FAQ description text

.github/workflows/stale.yml
- This PR will setup workflow to manage stale issues and pull-request. 
-  Closes #689 
**Summary**
This feature involves setting up a workflow to manage stale issues and pull requests (PRs) effectively. Stale issues and PRs can accumulate over time, leading to clutter and reduced productivity. By implementing this workflow, we aim to automatically identify and label stale issues and PRs based on predefined criteria. Additionally, the workflow will incorporate actions such as notifying contributors, closing stale items, or prompting for updates to keep the issue tracker organized and relevant. This feature will streamline issue and PR management, …
=> Feature : github-actions - Setup stale Issues and PRs workflow

data/validator-libraries-modern.yml
Update the doc to say that https://www.jsonschemavalidator.net/ supports 2020-12.
Is this all that is required to update https://json-schema.org/implementations?
=> Update online JSON Schema Validator to support 2020-12

.github/workflows/stale.yml, components/Sidebar.tsx, components/StyledMarkdown.tsx, pages/blog/posts/[slug].page.tsx, pages/blog/posts/understanding-lexical-dynamic-scopes.md
Fixing TableofContent at blog page. 
N/A
**Before**
**After**
N/A
**Summary**
N/A
N/A
=> Fix: ToC blog page fix

components/Sidebar.tsx
Update the alt text of icons so that the page is more accessible
I don't think there is any
This is how the page looks like if you disable JS in the browser.
I don't think it is relevant.
**Summary**
Somehow all icons had an `alt` text of `eye icon` even if they were different icons.
no.
=> fix: updated icon `alt`s

data/validator-libraries-modern.yml
sagold/json-schema-library supports Draft 2019, with some [minor caveats](https://github.com/sagold/json-schema-library/blob/773ace88126ba70203c1ed98c2697855de41d9a2/README.md?plain=1#L45-L49)
Updated docs to reflect this.
=> sagold/json-schema-library supports Draft 2019

components/Newsletter.tsx, components/NewsletterCard.tsx, data/newsletter.json, pages/newsletter/index.page.tsx
=> Refined Newsletter

data/validator-libraries-modern.yml
Most commands support everything from Draft 0 up to 2020-12. As an exception, the `test` and `validate` commands are Draft 4 for now (so I mentioned that in the notes), but we'll be quickly expanding that!
See: https://github.com/intelligence-ai/jsonschema
=> Mention the new Intelligence.AI JSON Schema CLI in the tools section

pages/blog/index.page.tsx
While clicking the tags in the blog page the query string will be updated  by blog's category.
-  Closes #703 
**Summary**
Query string added to tags. 
N/A
=> Feat: Adding query string to blog tags. 

data/validator-libraries-modern.yml
Follow up to https://github.com/json-schema-org/website/pull/715 now that it's publically released.
=> Update Json.NET Schema to support 2020-12

.github/workflows/links.yml
- Switches authentication from a personal token to a GitHub App authentication token for improved security. 
- Details why github-app? : https://github.com/json-schema-org/community/issues/741 
- Fixes the failing link.yml issue due to the token.
-  Related to  #719 
**Summary**
- No
=> chore(link.yml) : using github-app authentication and fixes failing link.yml workflow

components/DocsHelp.tsx
This PR aims to fix the unintentional behaviour of `Edit this page on Github` button inside `DocsHelp` component which directs the user to invalid file when the URL contains a hash fragment. This is achieved by utilising the existing `extractPathWithoutFragment` method in the `lib` directory which performs its function as suggested by name, to extract path after removing the fragment before its passed on to the link generator.
-  Closes #725  
No
=> [components][DocsHelp.tsx]: Fix "Edit this page on Github" fails when the URL contains a fragment

components/StyledMarkdown.tsx, pages/learn/getting-started-step-by-step.md, pages/md-style-guide.md, pages/specification-links.md
Removing warnings from Dev console 
-  Closes #760 
Warnings before change 
**Summary**
Warnings from dev console is removed.
=> Fix: Removing warnnings from console

pages/understanding-json-schema/structuring.md
`$ids` were changed to absolute URIs. A Draft-specific Info block that supports changing dialects in an embedded schema (using $schema with a different value than the parent schema) with an explanation of the difference between 2020-09 and 2020-12
refactoring doc
-  Closes #647  
**Summary**
=> I updated the base URI and included a Draft-specific info box section

data/tooling-data.yaml
This PR aims to improve the current data model for the website to enhance maintainability, completeness, and structure. The existing model primarily contains validators' data for the tooling section, while other data is hardcoded into the markdown files. This PR cleans unused and outdated fields, redesign the data model to consolidate all relevant data into a single file, and add maintainer details for future community events.
-  Closes #717 
-  Related to #716
-  Others? 
**Summary**
=> [data]: Data Preparation for Improved Data Model

.github/workflows/sync-contributors.yml, .github/workflows/sync-project-roadmap.yml
- This PR will create two workflows: one will fetch contributors' data, and the other will fetch project roadmap data.
-  Closes #775 
-  Related to #158 
-  Others? 
**Summary**
=> Added two workflows for fetching contributor and project roadmap data

data/validator-libraries-modern.yml
Also getting into Bowtie just now: https://github.com/bowtie-json-schema/bowtie/pull/1293. It supports Draft 4, 6, and 7, and I'm actively working on the rest (including older ones).
=> Add JSON Toolkit as a C++ implementation

.github/workflows/preview-deployment.yml, .github/workflows/production-deployment.yml
- This PR introduces two workflows: one for preview deployment and another for production.
- We are transitioning from native Cloudflare app deployment to our own manual workflow for both preview and production deployments.
- Since Cloudflare does not support previews from forked repositories, we are implementing manual deployment via GitHub Actions.
- Closes #330 
**If relevant, have you updated the documentation?**
**Summary**
- For complete details check out this comment : https://github.com/json-schema-org/website/issues/330#issuecomment-2115743948
=> [ github-actions ] : Add workflow to get preview from fork repository and deploy to cf pages

components/NextPrevButton.tsx, pages/learn/[slug].page.tsx, pages/learn/file-system.md, pages/learn/getting-started-step-by-step.md, pages/learn/json-schema-examples.md, pages/learn/miscellaneous-examples.md, public/icons/arrow.svg
=> Feat: Adding next-prev component

.github/workflows/trigger-update-landscape-tooling.yml
This PR aims to add a workflow, to track changes to the tooling data file and update tools in our landscape tooling category when tooling data changes.
NOTE: We need to add a fine-grained personal access token named `PERSONAL_ACCESS_TOKEN`, with `write` access to `Actions` of `landscape` repository to have appropriate authentication.
-  Others? 
**Summary**
=> Add workflow to update landscape tooling

README.md
closes #866 
This pull request corrects a minor typo in the documentation for setting up environment variables. The term "Enviroment" has been corrected to "Environment" for clarity and accuracy. This fix ensures that the documentation is clear and professional.
=> Fix Typo in Environment Variables Setup Section

.github/workflows/sync-contributors.yml, .github/workflows/sync-project-roadmap.yml
- Since we have branch protection rules, automated commits can't be made. Therefore, both workflows will now create pull requests instead.
- None
**Summary**
=> chore(github-actions): update contributor and project sync workflows

.github/workflows/stale-issues-prs.yml
**Summary**
This PR updates stale-issues-prs.yml to increase the number of days to mark an issue as stale from 30 to 180. The reason is the development speed is much slower so we need more range for such and operation.
=> Update stale-issues-prs.yml to increase the number of days to mark an issue as stale from 30 to 180

.github/workflows/validate-tooling-data.yml, data/tooling-data.schema.json, data/tooling-data.yaml, pages/tools/JSONSchemaTool.ts, pages/tools/components/ToolingDetailModal.tsx
This PR aims to sync up any added and changed data during the work progress to ensure the data is up to date and accurate before the final release.
Closes #776 #716
**Summary**
=> [data]: Sync and finalise tooling data

components/DocsHelp.tsx, cypress/components/DocsHelp.cy.tsx
This PR aims to update the DocsHelp Feedback component to use Google Sheets for feedback.
Closes #882 
**Summary**
=> [DocsHelp]: add DocsHelp Feedback to Google Sheets

data/tooling-data.schema.json, data/tooling-data.yaml, pages/tools/hooks/useToolsTransform.tsx
I haven't used the name "Hyperjump JSV" since v0. The release of the new tooling page reminded me to update it.
I also added a couple new categories that I think make sense: Annotations and Bundler. I added a couple other implementations to those categories that I knew for sure off the top of my head. We should probably make an announcement for others to update their listing if they support those features.
=> Rename @hyperjump/json-schema on tooling page and add new categories

data/tooling-data.yaml
In #925 I forgot there were two entries and only renamed one. @benjagm was so quick to merge that I didn't get the update pushed in time :smile:.
=> Rename json-schema.hyperjump.io on tooling page

data/tooling-data.yaml
Adds `cypress-ajv-schema-validator`
-  Closes #940
=> (Add) 940 cypress ajv validator

data/tooling-data.yaml
This PR aims to add the missing bowtie identifier for `@cfworker/json-schema` to fix the unavailable outlink to bowtie on the `/tools` page.
Closes: #976 
**Summary**
=> [tooling-data]: add @cfworker/json-schema bowtie identifer

pages/tools/components/Sidebar.tsx, pages/tools/hooks/useToolsTransform.tsx, pages/tools/index.page.tsx
This PR aims to add environment filter/search options to the new tooling data page at `/tools` as part of ongoing process to gather and iterate over community feedback to improve the page and minimise friction in JSON Schema tool adoption. 
Related: #928 
**Summary**
=> [tools]: Add environment filter/search options to tools

pages/learn/glossary.md
This pull request will add a definition for the `anchor` and `ref` terms to the glossary page as mentioned in this [comment](https://github.com/json-schema-org/website/issues/266#issuecomment-2065652423).  
-  Related to #266 
Depends on #677
No
**Summary**
This is a contribution to the ongoing effort to define the terms for JSON-Schema within a glossary page. 
No
=> feat: add glossary term for Anchor

.github/workflows/new-implementation.yml
bugfix
Closes https://github.com/json-schema-org/website/issues/755
Screenshots/videos:
No
**Summary**
This adds an additional condition to the existing check to trigger the action for first time contributors only for th path "data/tooling-data.yml"
Does this PR introduce a breaking change?
No
=> fix: modify the new-implementation.yml to trigger workflow on first PR

pages/specification/json-hyper-schema/_index.md
I noticed that the links on the hyper-schema page point to the raw xml on github. These links should point to the compiled and published documents. This PR fixes those links.
=> Fix hyper-schema page links

components/Layout.tsx
Bugfix
-  Closes #994
https://github.com/user-attachments/assets/4399559d-05a8-4a0d-8c7e-fc90e69ce834
No relevant
**Summary**
The error is due to re-rendering the children prop in a ternary operator
No
=> [Fix] Recall and re-render images in mobile

pages/draft-06/[slug].page.tsx, pages/draft-06/index.md, pages/draft-06/index.page.tsx, pages/draft-06/json-hyper-schema-release-notes.md, pages/draft-06/json-schema-release-notes.md, pages/draft-06/readme.md, pages/draft-07/[slug].page.tsx, pages/draft-07/index.md, pages/draft-07/index.page.tsx, pages/draft-07/json-hyper-schema-release-notes.md, pages/draft-07/json-schema-release-notes.md, pages/draft-07/readme.md, pages/draft/2019-09/[slug].page.tsx, pages/draft/2019-09/index.md, pages/draft/2019-09/index.page.tsx, pages/draft/2019-09/release-notes.md, pages/draft/2020-12/[slug].page.tsx, pages/draft/2020-12/index.md, pages/draft/2020-12/index.page.tsx, pages/draft/2020-12/release-notes.md, pages/specification/json-hyper-schema/_index.md, pages/specification/migration/index.page.tsx, pages/specification/release-notes/index.page.tsx, public/_redirects
**Summary**
After releasing the new structure of release notes making it a section of each spec version page we found that the redirect we created didn't. work in some scenarios producing some breaking changes. In addition, when embedding the release notes into the spec page we found that the fragments generated for subsections wasn't informative enough, therefore we are deciding to revert that change, making the release notes accessible as they were before.
Linked discussion:  https://github.com/json-schema-org/website/pull/955#issuecomment-2395593816
Issues:
- Related #955
=> [bug] - Revert release notes changes

pages/learn/glossary.md
- bugfix:when we are at the https://json-schema.org/learn/glossary#validation-result and click the validation result link it shows 404 error because the link is incorrect as it is not redirecting that page .Now the link is working correctly
-  Closes #1032
https://github.com/user-attachments/assets/f4ee09bc-2d0f-4325-9f54-09302d67a90f
No
No
=> fix broken link (#1032)

data/tooling-data.yaml
We extracted the JSON Schema validator out of the JSON Toolkit project into a project of its own, called "Blaze", which depends on JSON Toolkit.
Also see https://github.com/bowtie-json-schema/bowtie/pull/1593
=> Rename JSON Toolkit to Blaze

pages/community/index.page.tsx, pages/index.page.tsx
**Summary**
After upgrading the Google account, the previous calendar became private. We need to update the url.
=> Update calendar url after changing Google Account

data/keywords.yml
add some code for maxProperties keywords 
Issue #1052 
close #1052 
=> Fix: maxProperties Keyword Not Found in Documentation

CONTRIBUTING.md, README.md, components/Layout.tsx, pages/blog/generateRssFeed.tsx, pages/blog/posts/6-river-systems-case-study.md, pages/blog/posts/[slug].page.tsx, pages/blog/posts/applicability-json-schema-fundamentals-part-1.md, pages/blog/posts/bundling-json-schema-compound-documents.md, pages/blog/posts/code-of-conduct-for-json-schema.md, pages/blog/posts/hello-2023--hello-json-schema-community.md, pages/blog/posts/hello-world-hello-postman.md, pages/blog/posts/hyperborea.md, pages/blog/posts/json-schema-ambassadors.md, pages/blog/posts/json-schema-joins-the-openjsf.md, pages/blog/posts/new-website.md, pages/blog/posts/remote-case-study.md, pages/blog/posts/website-analytics-snapshot-2023.md
- Content update & maintenance
- Social media link modifications
N/A - URL updates only
Yes - All documentation files including README.md and CONTRIBUTING.md have been updated to reflect the new X.com nomenclature.
**Summary**
This PR implements comprehensive updates across our codebase to reflect Twitter's rebranding to X. Changes include:
Core Changes:
- Updated social media links from twitter.com to x.com
- Modified UI labels from "Twitter" to "X"
- Refreshed documentation references
Files Modified:
```
README.md
components/Layout.tsx
pages/blog/generateRssFeed.tsx
pages/blog/posts/6-river-systems-case-study.md …
```
=> Update references from Twitter to X in documentation and links.

CONTRIBUTING-docs.md
-  Closes #1097 
This PR updates the CONTRIBUTING-docs.md file to include instructions on adding metadata (YAML front matter) to new markdown files.
Added guidelines for including metadata fields like title, section, date, author, and tags.
=> fix: Update CONTRIBUTING-docs.md with instructions for adding metadata to markdown files

pages/ambassadors/index.page.tsx
fix typos for the naming `JSON Schema`
-  Others? 
**Summary**
=> fix: typos, should always include `JSON Schema`, not only `JSON`

.github/workflows/build-preview.yml, .github/workflows/production-deployment.yml
bug #1178  it clear Next.js cache in order to keep new css changes .
-  Closes #1178 
**Summary**
close #1178  remove cache to show latest change to css
no
=> fix: next.js cache issue

components/AmbassadorsBanner.tsx
-  Closes #1160 
-  Others? 
**Summary**
=> Bug Ambassadors Banner

Dockerfile, INSTALLATION.md
Added the corepack enable command  in the Dockerfile. This adjustment ensures that the correct version of Yarn is used consistently across different environments. 
Closes #1196 
Updated the 'Local Setup Using Docker' documentation to include steps for setting up the project locally for Windows users.
**Summary**
The current implementation of our Dockerfile, particularly for Windows users.
Key Issues:
1. Incompatibility with make Command
2. Yarn Version Mismatch Error
Solution:
To added the corepack enable command in the Dockerfile. This adjustment ensures that the correct version of Yarn is used consistently across different environments.
=> Update on Dockerfile Implementation for Windows Users

components/NavigationButtons.tsx, components/StyledMarkdown.tsx, pages/learn/[slug].page.tsx, pages/learn/file-system.md, pages/learn/json-schema-examples.md, pages/learn/miscellaneous-examples.md, pages/overview/[slug].page.tsx, pages/overview/case-studies/index.page.tsx, pages/overview/code-of-conduct/index.page.tsx, pages/overview/faq/index.page.tsx, pages/overview/roadmap/index.page.tsx, pages/overview/similar-technologies.md, pages/overview/sponsors/index.page.tsx, pages/overview/use-cases/index.page.tsx, pages/overview/what-is-jsonschema.md
-  Related to #1072 
**Summary**
I have created this PR to just verify that am I going in correct direction of solving the issue. Is this the thing that you wanted?
=> Add next prev button in Docs-->Overview

pages/specification-links.md
Added proper links for jsonschema-core.md and jsonschema-validation.md in specification-links.md
I have added proper links for jsonschema-core.md and jsonschema-validation.md.
https://github.com/json-schema-org/json-schema-spec/blob/main/specs/jsonschema-core.md
https://github.com/json-schema-org/json-schema-spec/blob/main/specs/jsonschema-validation.md
-  Closes #1239 ___ 
-  Others? 
**Summary**
NO
=> Added proper links for jsonschema-core.md and jsonschema-validation.md

pages/overview/case-studies/index.page.tsx
Replaces the Dummy Text present on https://json-schema.org/overview/case-studies page under the "Case Studies" header with some meaningful text
-  Closes #1236 
**Screenshot**
=> fix : remove dummy text present on https://json-schema.org/overview/case-studies page

data/tooling-data.yaml
This PR adds a new tool, JSV Elixir, to the available JSON Schema tooling.
-  Closes #1229 
-  Related to #1229
-  Others? No
- #### Image-1
- #### Image-2
**Summary**
This PR resolves Issue #1229 by adding the JSV Elixir library to the tooling list
No, this PR does not introduce breaking changes.
=> Added the JSV Elixir library to the avaiable tools

data/tooling-data.yaml
Feature: Added a new tool – JSON Schema Editor.
-  Closes #1118 
Documentation not required as this is a tool addition.
**Summary**
This PR introduces the JSON Schema Editor tool to the platform. It allows users to:
- Easily build JSON schemas using an intuitive UI.
- Convert JSON schemas into formats like SQL, GraphQL, and Protocol Buffers.
- Generate sample data conforming to the defined JSON schema.
- The addition enhances developer productivity by streamlining JSON schema creation and format conversions.
No breaking changes introduced.
=> [Feat]-Add json schema editor tool

data/tooling-data.yaml
This PR adds a new tool, Liquid JSON Schema Editor, to the list of tools. This editor supports graphical JSON Schema editing for multiple drafts and includes validation, documentation generation, and sample generation capabilities.
-  Closes #978 
**Summary**
The Liquid JSON Schema Editor is a feature-rich tool that simplifies the creation and editing of JSON Schemas for multiple drafts, including draft-04, draft-06, draft-07, 2019-09, and 2020-12. It also supports:
- Graphical editing: Provides an intuitive interface for designing JSON Schemas.
- Validation: Validates JSON files based on the selected JSON Schema.
- Documentation generation: …
=> [feat]-Add Liquid JSON Schema Editor

components/Layout.tsx, components/Sidebar.tsx, context.ts, pages/index.page.tsx, pages/pro-help/index.page.tsx
See: https://github.com/orgs/json-schema-org/discussions/779
=> Create a `/pro-help` page to promote the Contractors program

components/StyledMarkdown.tsx
What kind of change does this PR introduce?
🐛 Bugfix : Improves the contrast of bold text in dark mode.
Issue Number:
Closes #1248 
Before : [
]
After : 
If relevant, did you update the documentation?
No updates were needed as this is a UI bugfix.
Summary
This PR fixes a bug where bold text in dark mode had insufficient contrast, making it harder to read compared to light mode. The fix enhances the visibility of bold text while maintaining a cohesive design. This resolves a common complaint about text readability in dark mode. 
Does this PR introduce a breaking change?
No.
Additional Notes:
Tested on different devices and browsers to ensure consistency.
I didn't implement anything drastically new as all of it was aligned with the theme of the website.
=> 🐛 Bug #1248 fixed , [bold text harder to read]

pages/blog/index.page.tsx
Improved the blog category navigation section.
Previously it was scrolling up upon changing the tab but now its not doing so.
-  Closes #1287 
https://github.com/user-attachments/assets/cc284352-7fc9-4ca1-ab7c-f74343dc5dd2
**Summary**
=> Blog page Tab Improvement.

data/tooling-data.yaml
*What kind of change does this PR introduce?*
Feature: Added a new tool – @imhonglu/json-schema.
*Issue Number:*
-  Closes #1320 
*Screenshots/videos:*
https://github.com/user-attachments/assets/5b35dcc0-20fe-4dfd-80b6-978bb41f3331
*If relevant, did you update the documentation?*
Documentation not required as this is a tool addition.
*Summary*
This PR introduces the @imhonglu/json-schema tool to the platform. It supports static type inference for schema definitions and ensures validation based on the JSON-Schema-test-suite.
*Does this PR introduce a breaking change?*
No
=> feat: add @imhonglu/json-schema tool

pages/index.page.tsx
This PR updates the color of the URL displayed on the homepage in dark mode for improved visibility.
-  Closes #1267 
**Summary**
In dark mode, the URL on the homepage was underlined in black, making it difficult for users to identify. This PR changes the underline color to white, ensuring better visibility and enhancing usability.
No
=> Fix: URL color on homepage in dark-mode

pages/tools/components/ToolingDetailModal.tsx
-  Closes #1327 
[Screencast from 2025-01-19 02-05-36.webm](https://github.com/user-attachments/assets/eab21319-83e7-4fc9-9124-044879a66652)
**Summary**
=> feat: Added Esc functionality and improve styling of cancel button in ToolingDetail modal

data/tooling-data.yaml
Currently on the page the cypress-ajv-schema-validator is the only one that writes it Java**s**cript instead of Java**S**cript. Which means it ends up with it's own entry on:
https://json-schema.org/tools?query=&sortBy=name&sortOrder=ascending&groupBy=languages&licenses=&languages=&drafts=&toolingTypes=&environments=&showObsolete=false#javascript while also breaking the anchor link (since that one is 100% case insensitive).
=> Change cypress-ajv-schema-validator from Javascript to JavaScript

pages/tools/components/ToolingDetailModal.tsx
Bugfix: Ensures that tooling listing notes are processed as markdown.
-  Closes #1346 
[](https://github.com/user-attachments/assets/756231e5-0d54-4ae5-8c30-725e54099c9e)
No
**Summary**
This PR addresses the issue where tooling listing notes were not being processed as markdown. The raw markdown text was displayed instead of rendering correctly. The issue occurred due to a missing markdown parser in the rendering pipeline for these notes. The changes fix that
No
=> Fix - fix markdown render in tools page

pages/tools/components/ui/Checkbox.tsx, pages/tools/components/ui/DropdownMenu.tsx
Adding hover effect to sidebar of tools page 
Picture
Video 
[Screencast from 2025-01-22 10-32-59.webm](https://github.com/user-attachments/assets/a06a1e17-d66e-4e60-8492-fccc3cc0da49)
**Issue Number:** 
Closes #1216
https://github.com/json-schema-org/website/issues/1216
=> Add hover effects with cursor pointer

components/Sidebar.tsx, pages/overview/faq/index.page.tsx, pages/overview/pro-help/index.page.tsx, pages/overview/similar-technologies.md
1.  Pro Help Page Sidebar and Navigation Buttons:
- Added "Go Back" and "Up Next" buttons to the Pro Help page for consistent 
- Aligned the sidebar to match the logical flow of pages: Case Studies → FAQ → Pro Help → Similar 
- Fixed layout misalignment issues on the top and left of the Pro Help page.
2. Arrow Navigation Updates Across Pages
-  Closes #1291 
[Screencast from 2025-01-14 13-31-31.webm](https://github.com/user-attachments/assets/0676c54c-a336-4c44-8229-111ea2072204)
No
**Summary**
#1291  - Fixes Pro Help page sidebar alignment, adds navigation buttons, and standardizes arrow navigation across pages.
**Does this PR introduce a breaking …
=> Fix : pro help sidebar alignment and add buttons

pages/understanding-json-schema/reference/numeric.md
Documentation update
-  Closes #1113 
**Summary**
Add a note explaining the difference between float-point implementation of programming languages and json schema
No, it does not.
**Other**
I believe this note can be clearer, better if I also provide an example, not sure about it though. Please let me know about it.
=> docs: add note clarifying multipleOf implementation

.eslintrc.js
Removed terminal errors from .eslintrs.js file
-  Closes #1294 
**Screenshots:**
N/A
**Summary**
Removed terminal errors from .eslintrs.js file
N/A
=> fix: Removed terminal errors from .eslintrs.js file

components/JsonEditor.tsx, components/StyledMarkdown.tsx
This is a bugfix for the vertical alignment issue in the JSON schema example in the [documentation](https://json-schema.org/learn/getting-started-step-by-step#add-an-external-reference).
-  Closes #1293  
No.
**Summary**
The schema example under "To link to the external geographical location schema" had improper vertical alignment, specifically for the "warehouseLocation" key. This PR fixes the alignment issue, ensuring better readability and consistency in the example.
No
=> Fix: correct vertical alignment issue in schema example

pages/tools/components/ToolingDetailModal.tsx
Bowtie reports for tools are not loading 
-  Closes #1347  
https://github.com/user-attachments/assets/f876f3f2-cddb-4b62-94b7-c9b00d8b1cd3
**Summary**
To solve this, I replaced the onLoad logic with an asynchronous fetch request to check whether the image URL is valid and exists. While addressing this issue, I encountered a problem where the image loading wasn't being handled as expected using the onLoad event. Therefore, I implemented the asynchronous approach because onLoad was unable to properly render the component, which was preventing the data from being displayed.
=> Bug - solve the bowtie loading error

components/DarkModeToggle.tsx, cypress/components/DarkModeToggle.cy.tsx
Bugfix: Ensures the dark/light mode toggle closes automatically when the user clicks outside the toggle or interacts with other elements on the mobile view.
-  Closes #1281 
[Screencast from 2025-01-19 19-10-35.webm](https://github.com/user-attachments/assets/07bd17f8-1a5a-4ec4-b880-e812d72f3169)
No
**Summary**
#1281 - This PR resolves the issue where the dark/light mode toggle on the JSON Schema website did not close automatically when the user clicked outside it or interacted with other page elements in the mobile view.
=> fix[dark-mode-toggle]: fix dark/light mode toggle on mobile

data/tooling-data.yaml
This PR adds a new tool, micronaut-json-schema, to the JSON Schema Ecosystem page.
-  Closes #993 
[Screencast from 2025-01-22 14-20-26.webm](https://github.com/user-attachments/assets/6eab7966-9418-4ae0-a3be-86b537be1c02)
**Summary**
This PR adds the micronaut-json-schema tool to the JSON Schema ecosystem. The tool generates JSON Schema from Java classes and is part of the Micronaut framework. It supports the 2020-12 JSON Schema dialect and is categorized as a code-to-schema tool.
Details added to the YAML file include:
1. Tool name and description
2. Supported language (Java)
3. Tooling type (code-to-schema)
4. Maintainers (Micronaut Team)
5. …
=> feat[tools]: add micronaut json schema as tooling

pages/understanding-json-schema/reference/type.md
Currently the link doesn't resolve and points to a 404 page.
=> Fix broken link in `type` reference

pages/blog/posts/[slug].page.tsx, pages/overview/use-cases/index.page.tsx
Bug : Fix the image size on mobile device at latest blog page 
-  Closes #1480 
No
**Summary**
##Motivation
The current implementation of the image container uses a fixed height (`h-[500px]`), which causes display issues on mobile devices. This results in images appearing cropped or improperly scaled, leading to a suboptimal user experience.
##Testing
Tested across various devices:
- iPhone X (375x812)
- Galaxy(344x882)
- iPad Pro (1024x1366)
- Desktop (1920x1080)
##Additional Notes
This change enhances the responsiveness of image displays, improving the overall user experience on mobile devices.
No
=> Improve the image view on mobile device 

pages/blog/index.page.tsx
This bug fix will ensure all blog pictures are the same size, providing a more appealing and consistent appearance.
-  Closes #1434
no
=> adjusting the blog picture size

pages/understanding-json-schema/reference/metadata.md
Bug fix
-  Closes #1459
Not needed
**Summary**
This PR fixes an incorrect local URL  `http://localhost:3000//understanding-json-schema/reference/annotations` 
replacing it with the correct relative path `/understanding-json-schema/reference/annotations`.
in `metadata.md`
No
=> closes Bug: Annotation card link broken 

.github/workflows/README.md
Change few outdated links in .github/workflows README.md to latest changed link.
Closes #1418 
Changed url of github actions works - 
Change the docs of .github/workflows README.md.
**Summary**
Change few outdated links in .github/workflows README.md to latest changed link.
No
=> fix: few links in .github/workflows README

.github/pull_request_template.md, .github/workflows/pr-body-validation.yml
-  Closes #1123 
-  Related to #1123 
-  Others? 
N/A
**Summary**
This pull request introduces a GitHub Actions workflow that checks for essential information in pull requests. It ensures that contributors link relevant issues, answer key questions about their changes, and complete the checklist before submission. This enhancement aims to streamline the review process and improve communication regarding changes made in pull requests
- I have tested it many times looking forward for any improvements
- Everything is commented for the better understanding 
No, this PR does not introduce any breaking changes. …
=> Added Validation Workflow for Pull Request Content

pages/implementers/index.page.tsx
Fixed the "Go Back" button navigation on the implementers page by updating the URL from `/guides` to `/learn/guides`.
- Updated `prevURL` prop in `pages/implementers/index.page.tsx` to point to the correct guides page location
1. Go to the Implementers page
2. Click on the "Go Back" button
3. Verify that it correctly navigates to the guides page at `/learn/guides`
-  Closes #1511 
-  Others? 
https://github.com/user-attachments/assets/3b9668cf-c43b-4d50-a662-23d6cd5f435c
**Summary**
The "Go Back" button on the Implementers page was navigating to an incorrect URL (`/guides`), resulting in a 404 error. This PR fixes the navigation …
=> fix: Update Go Back button URL on implementers page

components/AmbassadorsBanner.tsx
bugfix
Closes #1524 
**Summary**
This PR fixes the issue on the Ambassadors page where the link at the bottom of the page incorrectly leads to the wrong section. The URL currently contains `#become-an-json-schema-ambassador`, but it should be `#become-a-json-schema-ambassador`. This update ensures the link navigates to the correct section when clicked.
no
- [x ] Read, understood, and followed the [contributing guidelines](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md).
=> adjusting the link in ambassador page

pages/blog/index.page.tsx
This will adjust the spacing of the header in the blog page and allow users to see the writer and their information more clearly.
-  Closes #1437
**Summary**
This PR ensures a good layout version for both desktop and mobile. It also makes sure that the articles and their writers are always visible.
no
=> adjusting blog page header

components/Sidebar.tsx
Keep overview section open when user click on pro-help in docs.
-  Closes #1416
No
**Summary**
Keep overview section open when user click on pro-help in docs just like all other links in docs
No
- [ y ] Read, understood, and followed the [contributing guidelines](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md).
=> fix: keep overview section open when user click on pro-help in docs

pages/index.page.tsx
This PR fixes a minor spacing issue in the sponsor section text. Previously, the text appeared as "sponsoror a" due to a missing space after the sponsor link. 
- Added a space after the `</a>` tag to correctly separate the words.
This is a minor text fix to improve readability. 🚀
-  Closes #1553  
NO
=> fix: add missing space in sponsor section

.github/workflows/ci.yml
Chore / Security Patch
-  Related to https://json-schema.slack.com/archives/C8C4UBXDF/p1742201444695489
**Summary**
Temporarily disables the check for unauthorized file changes in the GitHub Actions workflow due to known security vulnerabilities. This is a precautionary measure until a safer implementation is available.
No
=> chore: disable unauthorized file change check due to known vulnerabilities

pages/learn/getting-started-step-by-step/getting-started-step-by-step.md, pages/understanding-json-schema/basics.md
This PR adds a missing ending colon in the `basics.md`.
N/A
N/A
N/A
**Summary**
N/A
N/A
=> Polish docs

components/Layout.tsx, pages/blog/index.page.tsx, pages/community/index.page.tsx, pages/index.page.tsx
Make entire button area clickable by applying styles directly to <a> tag
-  Closes #1562
=> Fix: Make entire button area clickable by applying styles directly to <Link> 

pages/index.page.tsx
bugfix
**Summary**
A while back we migrated our google account and the calendar changed. I thought the website was updated to the new calendar. Don't know if the update got reverted at some point or I was just wrong. Anyway, this points it to the right place.
No
=> Update calendar links to point to the info@json-schema.org calendar

data/tooling-data.yaml
An update to the Tooling page. It updates the `@remoteoss/json-schema-form`
=> Update tooling-data.yaml - Update @remoteoss/json-schema-form

data/tooling-data.yaml
tooling-data: Update @remoteoss/json-schema-form maintainers. Follow-up of https://github.com/json-schema-org/website/pull/1671
**Issue Number:** N/A
=> tooling-data: Update @remoteoss/json-schema-form maintainers

pages/blog/index.page.tsx
Feature – This PR allows blog posts to belong to multiple categories instead of just one. and improve the filtering to filter more than one category
-  Closes #1425 
*I added the category to the blog only for the example picture and did not actually change the blog in the pic.
**Summary**
- The blog data structure is updated to support an array of categories.  
- The UI now renders each category as a separate clickable badge.  
- Users can filter by multiple categories at once.  
- Filtering logic has been improved to sort posts by the number of matching categories when multiple filters are selected.  
Blog posts now support multiple categories by framing them like this in the blog file:  
```yaml …
```
=> Enhanced category filtering

pages/tools/components/ToolingTable.tsx
This PR will adjust the tables on the tools page for mobile and improve the desktop table to prevent it from being cut off, ensuring users don't need to scroll sideways to view the full length of the table.
-  Closes #1442
**Summary**
I think this is a necessary change, as it will improve the readability of the tools on the page.
no
=> Tools Page Table mobile Adjustments

pages/tools/components/Sidebar.tsx, pages/tools/hooks/useToolsTransform.tsx
This PR adds a new filter option on the tools page that allows users to display only tools supporting Bowtie.
-  Closes #1550
**Summary**
- Introduces a new checkbox labeled “Support Bowtie” in the sidebar filter.
- Updates the filtering logic and transform hook to include Bowtie support.
- Enables users to quickly find tools that are compatible with or validated by Bowtie.
no
- [ x] Read, understood, and followed the [contributing guidelines](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md).
=> Filter for tools supporting bowtie

pages/learn/getting-started-step-by-step/getting-started-step-by-step.md, pages/learn/getting-started-step-by-step/index.page.tsx, pages/learn/glossary.md, pages/learn/index.page.tsx, pages/learn/json-schema-examples.md, pages/learn/miscellaneous-examples.md, pages/specification.md, pages/understanding-json-schema/reference/comments.md, pages/understanding-json-schema/reference/non_json_data.md, pages/understanding-json-schema/reference/schema.md
- bugfix: This PR fix all incorrect navigations throughout JSON Schema website that were mentioned in issue #1647 
Old incorrect navigations : 
- Get Started Overview -> Creating your first Schema
- Get started overview <- Create your first schema -> Miscellaneous Examples
- Other examples <- Json schema glossary -> JSON schema keywords
- JSON schema glossary <- Miscellaneous examples
- Other examples -> JSON Schema glossary
- Dialect and vocabulary declaration -> Value restrictions
- Comments -> Enumerated values
- JSON schema reference <- Specification overview 
Modified Correct navigations : 
-  Closes #1647  
Sample relevant screenshot is attached below.
**If relevant, did you update the …
=> fix: Incorrect page navigation throughout JSON Schema website

components/ui/input.tsx, cypress/components/Checkbox.cy.tsx, cypress/components/SearchBar.cy.tsx, pages/tools/components/SearchBar.tsx, pages/tools/components/ui/Checkbox.tsx, pages/tools/index.page.tsx
- Adapts two components to the ShadCN library:
- **Checkbox** component (improved with fill states, a hover effect, and proper containment)
- **SearchBar** component (migrated without visual changes)
- Creates and adjusts Cypress test files for both components to ensure reliability and behavior coverage.
- Fixes issue #1279 by making the Tools filter sidebar fixed to the side of the viewport.
- Closes #1279
- Related to #1656
- **Checkbox component before adjustment:**
- **Checkbox component after adjustment:**
> *The SearchBar component looks exactly the same after migration to ShadCN.*
**Summary**
This PR:
- Migrates the existing **Checkbox** component to the ShadCN library.
- Enhances styling with …
=> Adapt Checkbox & SearchBar to ShadCN, Add Tests, and Fix Tools Filter position

pages/tools/components/ToolingTable.tsx, public/icons/icons8-info.svg
-  Closes #1640 
**Summary**
Before: Tools without Bowtie integration showed a cross (❌) icon, suggesting an error or problem. After: These tools now show an information (ℹ️) icon, indicating that additional information is available.
No
=> enchance the Bowtie Column Icon

components/StyledMarkdown.tsx
Improve the readablity of text in [Boolean reference page](https://json-schema.org/understanding-json-schema/reference/combining).
Closes #1564 
No
No
- [ y ] Read, understood, and followed the [contributing guidelines](https://github.com/json-schema-org/website/blob/main/CONTRIBUTING.md).
=> fix: improve the readablity of text in Boolean reference page

data/tooling-data.yaml
Tools addition: Through this PR, three new tools: ya-json-schema-types, core-ajv-schema-validator and json-schema-describes-subset have been added to tools page
-  Closes #1384  
-  Closes #1631 
-  Closes #1635 
No
**Summary**
New tools are added :
- ya-json-schema-types
- core-ajv-schema-validator
- json-schema-describes-subset
No
=> Add ya-json-schema-types, core-ajv-schema-validator, and json-schema-describes-subset to tools page

components/AmbassadorsBanner.tsx, components/AmbassadorsCard.tsx, components/AmbassadorsList.tsx, cypress/components/AmbassadorsBanner.cy.tsx, cypress/components/AmbassadorsCard.cy.tsx, cypress/components/AmbassadorsList.cy.tsx
- Adapted 3 components to use the ShadCN library.
- Created and adjusted Cypress test files for these 3 components 
- Added animation to the ambassador card when pressing on the 'full details' button.
- standardized all the image sizes on the ambassadors card
- Closes #1478 
- Closes #1556 
- Related to #1657 
https://github.com/user-attachments/assets/7f569de0-56cb-4f15-83fe-da88c2175762
> The banner and list components look completely the same.
**Summary**
This PR:
- Migrated the existing `AmbassadorsCard.tsx`, `AmbassadorsBanner .tsx`, and `AmbassadorsList ` components to the ShadCN library.
- Enhanced the overall styling (mainly small color theme and light mode changes).
- Added Cypress tests for …
=> Migrate AmbassadorsCard, AmbassadorsBanner and AmbassadorsList to ShadCN  +2 issues resolved

.github/workflows/pr-body-validation.yml
This PR basically updates the previous approach of referencing issues with a new one that supports:  
- All types of official GitHub-recognized keywords for issue references which includes : 
close 
closes
closed
fix
fixes
fixed
resolve
resolves
resolved
- Full URLs to issues (not just the # 1234 format).
-  Closes #1739  
**Summary**
Update the PR Body Validation workflow to accept:
- Full URLs to issues (not just the # 1234 format).
- Any of the official GitHub-recognized keywords for issue references.
This would make PR validation consistent with GitHub’s own behavior and reduce friction for contributors who use the full range of supported formats.
No
Please ensure the …
=> Updated PR body validation workflow

data/tooling-data.yaml
Docs state that Pydantic generates JSON Schema Draft 2020-12:
https://docs.pydantic.dev/latest/concepts/json_schema/
tooling-data: Update Pydantic information
**Issue Number:** N/A
=> tools: Update Pydantic homepage and dialects

components/StyledMarkdown.tsx, pages/blog/posts/oracle-case-study.md
Bugfix fixes incorrect entries in the blog Table of Contents (TOC)
-  Closes #1744
**Summary**
the issue was dealing with the Infobox element, by adding it to the hidden elements in the StyledMarkdown component we can remove it from the TOC
no
=> Fixing TOC bug in blogs

components/CarbonsAds.tsx, components/Layout.tsx, components/ScrollButton.tsx, components/Sidebar.tsx, components/SiteLayout.tsx, cypress/components/ScrollButton.cy.tsx, cypress/components/Sidebar.cy.tsx
- Adapted 2 components to use the ShadCN library.
- Created and adjusted Cypress test files for these 2 components, significantly improving code maintainability.
- Adjusted for dark mode the scroll button
- Made the hover effects and styling of the sidebar consistent with the sidebar on the Tools page.
- Solved a bug issue
- Closes #1559 
- Related to #1658 
> A dark mode state have been added to the scroll button
**Summary**
This PR:
- Migrated the existing `Sidebar.tsx` and `ScrollButton.tsx` components to the ShadCN library.
- Enhanced the overall styling (add dark mode for the ScrollButton and made the sidebar styles consistent with the tools page sidebar).
- Added Cypress tests for all …
=> Migrate Sidebar and ScrollButton to ShadCN + issue resolved

components/Headlines.tsx, components/Layout.tsx, cypress/components/Headlines.cy.tsx, cypress/components/Layout.cy.tsx, pages/blog/index.page.tsx
Adapted the layout and headlines components to use ShadCN and updated the Cypress tests accordingly.
Added hover effects for the blog cards (the image and title will get bigger) added a read more section and adjusted the image sizes of the cards to be the same size (this was resolved before but for some reason the issue appeared again)
-  Closes #1330 
-  Closes  #1658 
https://github.com/user-attachments/assets/8c389b3e-2b42-49ce-8ada-f341d71f02ef
> The adapted components look the same
**Summary**
this PR solve an issue in the blog page and adapts 2 component to ShadCN while adjusting the tests and keeping a full coverage 
no
Please ensure the following …
=> Adapting layout and headlines components to ShadCN + issues resolved 

pages/blog/index.page.tsx
Bugfix - reduces the height of the banner on the blog page
-  Closes #1780 
**Summary**
The current blog page banner takes up too much vertical space. This PR adjusts the banner's height and padding.
no
=> fixing blog banner

data/tooling-data.yaml
This PR adds the Blaze4J tool to the tooling-data.yaml file. Blaze4J is a high-performance Java wrapper for the Blaze JSON Schema validator, built as part of GSoC '25.
-  Closes #1836 
**Summary**
This PR adds the Blaze4J tool to the `tooling-data.yaml` file. Blaze4J is a high-performance Java wrapper for the Blaze JSON Schema validator, built as part of Google Summer of Code 2025 (GSoC '25).
**Key Highlights**
- Support for JSON Schema drafts: 2020-12, 2019-09, draft-07/06/04
- Custom resolvers: HTTP and classpath-based
- Cross-platform compatibility: Windows, Linux, macOS
- Detailed validation and rich error reporting
- Clean and intuitive Java API for seamless …
=> feat: Add Blaze4J tool to tooling data
